### ISSUE TITLE
feat: Caterer on figure eight

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1003]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/88497451-58191080-cffb-11ea-97a8-afa07b2abb34.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/caterer-on-figure-eight.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!  

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by omer-mohamed** [comment]
I'll do this!
