### ISSUE TITLE
feat: Caterer on Jason's p22

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1004]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/88497498-8696eb80-cffb-11ea-9777-edfed0dda03e.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/caterer-on-jasons-p22.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!  

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by omer-mohamed** [comment]
Can I work on this as well?
