### ISSUE TITLE
feat: Caterer on Merzenich's p31

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1005]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/88497553-b2b26c80-cffb-11ea-84d7-2cb1447955d4.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/caterer-on-merzenichs-p31.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!  

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by omer-mohamed** [comment]
I can help with this!
