### ISSUE TITLE
feat: Caterer on rattlesnake

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1006]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/88497652-fc02bc00-cffb-11ea-83ae-19450b9c11b7.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/caterer-on-rattlesnake.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!  

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by omer-mohamed** [comment]
Can I work on this?
