### ISSUE TITLE
feat: Caterer

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1016]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/88882605-4e96df00-d26d-11ea-9fe2-7eab0ea83b2c.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/caterer.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!  

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by roniel-rhack** [comment]
Let me do it
