### ISSUE TITLE
feat: Cis-beacon down on long hook

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1017]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/88882774-7c7c2380-d26d-11ea-851d-b0138a307b95.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/cis-beacon-down-on-long-hook.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!  

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by techieParth** [comment]
May I talk this issue?
