### ISSUE TITLE
feat: Cis-beacon on anvil

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1018]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/88882828-a3d2f080-d26d-11ea-92da-290d48d0d4c0.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/cis-beacon-on-anvil.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!  

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by Rkv88** [comment]
i'll do it 😘
