### ISSUE TITLE
feat: Cis-beacon on cap

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1019]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/88882878-ca912700-d26d-11ea-9429-26398016ccda.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/cis-beacon-on-cap.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!  

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by SouradipPoddar** [comment]
Hi, I'll work on this one!
