### ISSUE TITLE
feat: Cis-beacon on dock

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1020]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/88882950-f7ddd500-d26d-11ea-9d7a-b758c22eddca.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/cis-beacon-on-dock.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!  

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by roniel-rhack** [comment]
I wanna do it

**Comment by elior8900** [comment]
Assign me please, thanks.
