### ISSUE TITLE
feat: Cis-beacon on table

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1021]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/88882996-1e9c0b80-d26e-11ea-85b9-e77c55559e80.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/cis-beacon-on-table.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!  

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by SerjTheDoctor** [comment]
I would like to take this one
