### ISSUE TITLE
feat: Cis-beacon up on long hook

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1024]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/89124956-e0287a00-d515-11ea-848f-0cdb865f2423.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/cis-beacon-up-on-long-hook.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!  

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by rstor1** [comment]
I can try this one if no one else has claimed it.
