### ISSUE TITLE
feat: Cis-boat on long hook eating tub

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1025]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/89124987-0b12ce00-d516-11ea-8cd3-f90e0c02db5f.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/cis-boat-on-long-hook-eating-tub.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!  

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by siddharth2411** [comment]
I'd like to take this up.
