### ISSUE TITLE
feat: Claw test tube baby

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1026]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/89125099-fc78e680-d516-11ea-859b-e3f00131b481.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/claw-test-tube-baby.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!  

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by Samir70** [comment]
I'll have a go at this if you like.
