### ISSUE TITLE
feat: Coe's p8

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1027]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/89125138-35b15680-d517-11ea-8ec9-3bd895523c23.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/coes-p8.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!  

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by roniel-rhack** [comment]
Let me do it
