### ISSUE TITLE
Nodemon as devDependency?

### ISSUE THREAD

**Issue by rstor1** [TroyTae/game-of-life#1034]
Hi,

Not an issue, more of a question: Would it be beneficial to add Nodemon automation as a devDependency in the project? If so, I wouldn't mind trying to add it in.

Thanks,

Ryan

**Comment by TroyTae** [comment]
Isn't `webpack-dev-server` already doing that?? 🤔

**Comment by rstor1** [comment]
Yes, you are right it does. I was mistaken because it was not happening while editing the .json files but it indeed does it for .ts files. Sorry about that. 

While we are here, what about adding a --progress flag on start?
