### ISSUE TITLE
error while parsing tsconfig.json

### ISSUE THREAD

**Issue by rstor1** [TroyTae/game-of-life#1036]
Hi,

I am getting a build failure when trying to run the app. Here is a sample error:

`ERROR in ./src/build/oscillator/billiard-table/chemist.ts
Module build failed (from ./node_modules/ts-loader/index.js):
Error: error while parsing tsconfig.json
    at Object.loader (C:\Users\ryan.storm\Documents\game-of-life\node_modules\ts-loader\dist\index.js:19:18)
 @ multi (webpack)-dev-server/client?http://localhost:4200 build/oscillator/billiard-table/chemist.ts oscillator/billiard-table/chemist[1]`

I saw that the tsconfig file was removed from: **https://github.com/TroyTae/troyjs**, so I am assuming that is the reason?

**Comment by TroyTae** [comment]
Oops thank for find this 😅 
fixed by c7de6d4
