### ISSUE TITLE
feat: Confused eaters

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1041]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/89731937-1b7ef780-da86-11ea-9df8-a50ff00e9f4a.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/confused-eaters.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by vozalel** [comment]
I want it!
