### ISSUE TITLE
feat: Cross 2

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1042]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/89731959-3c474d00-da86-11ea-929b-deedf0e41ac3.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/cross-2.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by vozalel** [comment]
I want to take up this issue, may I help?
