### ISSUE TITLE
feat: Cross

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1043]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/89731977-613bc000-da86-11ea-975b-d49f6fa409e7.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/cross.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by vozalel** [comment]
I want to take up this issue, may I help?
