### ISSUE TITLE
feat: Crown

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1044]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/89731994-80d2e880-da86-11ea-954c-a1f7a0cc5603.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/crown.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by techieParth** [comment]
I want to take up this issue,may I work?

**Comment by TroyTae** [comment]
Sure!
