### ISSUE TITLE
feat: Bookends

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#105]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/66713474-612b4f00-ede6-11e9-97af-02ed0595e4f8.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/bookends.ts

**Comment by nicm42** [comment]
I can do this.

**Comment by TroyTae** [comment]
Cool!
