### ISSUE TITLE
Improved UI

### ISSUE THREAD

**Issue by titivermeesch** [TroyTae/game-of-life#1055]
I would propose to make a better design to display all the possible starting grids.
I was thinking about a grid like view with little previews of each scenario.

**Comment by titivermeesch** [comment]
I'm working on a prototype of it

**Comment by titivermeesch** [comment]
@TroyTae I have a little question about how this project is put together. Right now it seems like it's server side rendered.

Do you think it is a good idea to have a custom visualizer to preview a "Life"? Because trying to use the canvas on the server itself seems to bring a lot of issues.

**Comment by elior8900** [comment]
if you need help, I did some digging, the html is created by the script in:
src\template\index.js

and the css is generated from this file:
src\style.css

it creates a <div> for each <a>, I would change it and use the hirarchy to control the items inside (tried some flex with coloum flex direction)
the problem is that some .js files are not in a specific category folder so it gets weird to control the output (dont really know how to change that without breaking the code).

demo:
![image](https://user-images.githubusercontent.com/12694677/92304409-49bcfd80-ef86-11ea-806b-5415bc588f35.png)

**Comment by NitinNair89** [comment]
@titivermeesch  Sharing few thoughts:

I was thinking whether we can revamp the overall UI for this website. Maybe something similar to Codepen.io would be cool to have, no?

If the landing page is divided into "sections" and each section is further divided into "Cards" then each element can reside in the card. The card can have more details like when it was created, purpose of element, etc.

For example, "1 beacon" will have its own card, and that card would show details like:
- Name
- Purpose

>  I was thinking about a grid like view with little previews of each scenario.
I thought the same at first, but for the preview to work, we may have to scale down the functioning UI. Some of the elements are big and take up entire viewable area in the browser.

**Comment by titivermeesch** [comment]
@NitinNair89 Yes that is what I was thinking of as well. I was also thinking that those cards could have a static preview of what the game looks like, but I couldn't figure out a good way to do this just yet.

**Comment by NitinNair89** [comment]
> @NitinNair89 Yes that is what I was thinking of as well. I was also thinking that those cards could have a static preview of what the game looks like, but I couldn't figure out a good way to do this just yet.

@titivermeesch 
As far as I understand, everything is in `index.tsx` file. You just have to add styles to it I believe. Any small CSS package should help.

**Comment by titivermeesch** [comment]
@NitinNair89 Yeah I get that, but I can't find a good way to "preview" the lifes

**Comment by NitinNair89** [comment]
@titivermeesch you can open this project using gitpod.io and see previews. Or you can ask @TroyTae for instructions to setup local dev environment in your system.

@TroyTae - Have a look at this CSS library. Do you think it would benefit?

**Comment by TroyTae** [comment]
What kind of css library are you saying??

**Comment by NitinNair89** [comment]
> What kind of css library are you saying??

Oops. I forgot to share the link - https://purecss.io/layouts/

**Comment by titivermeesch** [comment]
@NitinNair89 I don't think you got what my problem was 😄 
My mean idea was to have a preview, a static image of life, the arrangement of the white and black squares.
