### ISSUE TITLE
feat: Double caterer

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1059]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/90653178-d58e1480-e279-11ea-8765-767092344c2d.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/double-caterer.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by JusteenR** [comment]
Hi, I'd like to take this issue.
