### ISSUE TITLE
feat: Bookends siamese tables

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#106]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/66713484-7d2ef080-ede6-11e9-82e7-a9f4533eea63.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/bookends-siamese-tables.ts

**Comment by marfgold1** [comment]
I'd like to work in this issue! It's just converting those pixels into arrays of 1 or 0, right?

**Comment by TroyTae** [comment]
@marfgold1 
That's right!
Thank you for your interest :)
