### ISSUE TITLE
build: prebuild only changed file

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1061]
When execute `npm run prebuild`, now every json files are generated.
Generate only changed files for optimizing.

**Comment by elior8900** [comment]
Can I have it?

**Comment by TroyTae** [comment]
@elior8900 
Yes that's right!
`prebuild` script is here:
https://github.com/TroyTae/game-of-life/blob/559be68c463d632619f88a2abb25167431085b98/package.json#L15

**Comment by elior8900** [comment]
I think I have it done, just checking if the .ts file doesnt exist or the the .json was changed after the .ts was changed.
(checkd it it works).
adding this if before building:
![image](https://user-images.githubusercontent.com/12694677/92215458-7d702880-ee9d-11ea-95e7-68f167df0c0c.png)
