### ISSUE TITLE
feat: Dueling banjos

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1066]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/90979948-404d9180-e593-11ea-9612-66a25691ec72.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/dueling-banjos.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by joshgrime** [comment]
Hi, I'd like to take this issue please
