### ISSUE TITLE
feat: Eater/block frob

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1067]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/90979978-68d58b80-e593-11ea-9c6d-b38b81f8d177.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/eater-block-frob.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by AzzerAce** [comment]
I will do it.
