### ISSUE TITLE
feat: Eater plug

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1068]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/90979995-902c5880-e593-11ea-83dd-45453646d773.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/eater-plug.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by mariapash** [comment]
Hi, can I work on this issue please?
