### ISSUE TITLE
feat: Electric fence

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1069]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/90980010-afc38100-e593-11ea-81f5-04f643b2fecf.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/electric-fence.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by brandedcow** [comment]
Hi, I'll try this one.
