### ISSUE TITLE
feat: Broken elevener

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#107]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/66713491-90da5700-ede6-11e9-9428-806ff1d88f04.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/broken-elevener.ts

**Comment by marfgold1** [comment]
Hello, I want to work in this issue too 😄

**Comment by TroyTae** [comment]
@marfgold1 Cool!
