### ISSUE TITLE
feat: Elkies' p5

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1072]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/91188921-ce10b480-e72c-11ea-9598-3cd9e7a294af.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/elkies-p5.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by mariapash** [comment]
Hi, I'd like to work on this issue :)
