### ISSUE TITLE
feat: Ellison p4 HW emulator

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1074]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/91189142-0c0dd880-e72d-11ea-8e0c-05861ba2e246.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/ellison-p4-HW-emulator.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by khabiirk** [comment]
Hi,

I would like to work on that if thats okay
