### ISSUE TITLE
feat: Extremely impressive

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1075]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/91189243-2d6ec480-e72d-11ea-9575-adadd3941fe1.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/extremely-impressive.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by SampathKumar27896** [comment]
Hi TroyTae, I am a first time contributor and I would like to work on this issue.
