### ISSUE TITLE
feat: Diamond ring

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1080]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/91529335-0e964b00-e944-11ea-8a63-3e3f3a879cbc.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/billiard-table/diamond-ring.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by LauraRe** [comment]
Hi! I would like to work on this issue :)
