### ISSUE TITLE
feat: En retard

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1081]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/91529420-3a193580-e944-11ea-8fe1-dd09038ec928.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/billiard-table/en-retard.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by sannamar** [comment]
I can do this!
