### ISSUE TITLE
feat: Decapole

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1082]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/91529515-659c2000-e944-11ea-925f-7505b5f63693.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/muttering-moat/decapole.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by kshida** [comment]
Hi, I'd like to work on this issue :)
