### ISSUE TITLE
feat: Duodecapole

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1083]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/91529594-88c6cf80-e944-11ea-9df7-e48f58b42fd9.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/muttering-moat/duodecapole.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by vucong2409** [comment]
Hi! I would like to work on this issue :)
