### ISSUE TITLE
feat: Double X

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1088]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/91651010-0a903780-eac2-11ea-8c09-7bedb4c6c53f.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/relay/double-x.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by muskanvk** [comment]
Hii ! I am interested in taking up this issue. What needs to be done ? As far as I understood, we have to make patterns and then raise a PR right ? I'm a bit confused.

**Comment by TroyTae** [comment]
@muskanvk 
Yes that's right!
Make a pattern and send us PR following guide

**Comment by wimanshaherath** [comment]
hi! I am interested to take up this issue.

**Comment by SeekerNik** [comment]
hey @wimanshaherath you copied my work and now you are requesting PR. 🙄

**Comment by wimanshaherath** [comment]
@SeekerNik  I didn't copy anything..  this is my own work. If you want to see how did i do it, I can show you the evidence

**Comment by TroyTae** [comment]
@wimanshaherath 
Thank you for your interst!
But @SeekerNik send us first, so now I'm closing your PR.
Please check comment and referenced PR for preventing duplicate in the future :)
