### ISSUE TITLE
feat: Diuresis

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1089]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/91651026-36132200-eac2-11ea-8be9-8081254d493e.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/shuttle/diuresis.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by lalmqvist** [comment]
I'd like to do this one 👍  :)
