### ISSUE TITLE
feat: Eureka

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1090]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/91651045-61960c80-eac2-11ea-8c25-7d5645f98ffa.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/shuttle/eureka.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by harsha218** [comment]
I will take this

**Comment by harsha218** [comment]
Hey TroyTae, I have followed all the steps in CONTRIBUTION.md 
but facing issue in PR
