### ISSUE TITLE
feat: Four boats

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1104]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/92323842-d3e48f00-f076-11ea-8d15-772a59bfb679.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/babbling-brook/four-boats.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by alexanderbrown21** [comment]
i can work on this!

**Comment by SeekerNik** [comment]
it's done.

**Comment by alexanderbrown21** [comment]
ahh okay that's no problem.
