### ISSUE TITLE
feat: Great on-off

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1105]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/92323861-00001000-f077-11ea-8b7f-33a26a0818d8.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/babbling-brook/great-on-off.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by CalistusK** [comment]
Hi, I'd like to handle this one. Thanks!
