### ISSUE TITLE
feat: Light bulb

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1106]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/92323874-1b6b1b00-f077-11ea-9020-e715a1eadfdf.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/babbling-brook/light-bulb.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by Aditya-Srivastav** [comment]
I'd like to do this :)
