### ISSUE TITLE
feat: Fore and back

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1109]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/92423350-cc7ace00-f1bb-11ea-8ab5-f2f6dd61ee55.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/billiard-table/fore-and-back.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by vivienhennig** [comment]
Hey, I would like to do it :)
