### ISSUE TITLE
feat: Frog II

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1110]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/92423402-f3390480-f1bb-11ea-8ced-9fcb9c7ca8a2.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/billiard-table/frog-II.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by Rkv88** [comment]
sent PR pls review&accept

also  when running  `npm run start`    i get errors  
![image](https://user-images.githubusercontent.com/42079229/92533691-a563e100-f23b-11ea-9e7c-ab5e495f67c4.png)
