### ISSUE TITLE
feat: Germ

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1111]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/92423444-1b286800-f1bc-11ea-8ebc-07baf1d2a506.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/billiard-table/germ.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by SeekerNik** [comment]
done
