### ISSUE TITLE
feat: Hertz oscillator

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1112]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/92423513-532fab00-f1bc-11ea-97e4-12d4ff47d89d.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/billiard-table/hertz-oscillator.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by SeekerNik** [comment]
I'm on it.
