### ISSUE TITLE
feat: Hustler II

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1116]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/92542620-3363ba00-f284-11ea-97ef-2b0d4b2aabf1.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/billiard-table/hustler-II.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by alexanderbrown21** [comment]
i'll take this one on. the other one was already done by another contributor!

**Comment by manolasco** [comment]
I'd like to try
