### ISSUE TITLE
feat: Hustler

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1117]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/92542673-5c844a80-f284-11ea-8035-e18c286fb612.png)

Please work at this file:  https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/billiard-table/hustler.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by stebunting** [comment]
I can do this one
