### ISSUE TITLE
feat: Loading dock

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1118]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/92542962-2a271d00-f285-11ea-8f2a-1222ed7d0537.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/billiard-table/loading-dock.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by SeekerNik** [comment]
On it.
