### ISSUE TITLE
feat: Mathematician

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1119]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/92543030-53e04400-f285-11ea-8380-798c97da0df0.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/billiard-table/mathematician.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by SeekerNik** [comment]
On it.
