### ISSUE TITLE
feat: Mini pressure cooker

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1125]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/92723945-cbf15b80-f3a4-11ea-95da-83d564d27ac5.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/billiard-table/mini-pressure-cooker.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by jad837** [comment]
I would like to work on this.
