### ISSUE TITLE
feat: Negentropy

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1126]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/92724011-e592a300-f3a4-11ea-941b-1002ac3a314b.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/billiard-table/negentropy.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by hauchongtang** [comment]
I would like to work on this.

**Comment by hauchongtang** [comment]
#1131
