### ISSUE TITLE
feat: New five

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1127]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/92724076-01964480-f3a5-11ea-97cd-6d555fe1b536.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/billiard-table/new-five.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by vandana1499** [comment]
I will like to work on this.

**Comment by minierparedes** [comment]
Would like to contribute to the project.
