### ISSUE TITLE
feat: Gray counter

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1135]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/93038122-17df2180-f67f-11ea-9753-4ca02742f6ac.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/muttering-moat/gray-counter.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by yarden2k3** [comment]
I opened a PR regarding this pattern :)
