### ISSUE TITLE
feat: Heptapole

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1136]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/93038187-44933900-f67f-11ea-99a1-679cf33518fa.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/muttering-moat/heptapole.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by meyerv11045** [comment]
I'd like to take this issue
