### ISSUE TITLE
feat: Muttering moat 1

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1138]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/93038264-7dcba900-f67f-11ea-9cdb-c573f05a3bbd.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/muttering-moat/muttering-moat-1.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by mick4711** [comment]
I'd like to tackle this issue @TroyTae

**Comment by TroyTae** [comment]
@mick4711 Please request another after finish one issue :)

**Comment by mick4711** [comment]
Sorry about that @TroyTae ... one at a time OK!
