### ISSUE TITLE
feat: Nonapole

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1139]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/93038392-d13df700-f67f-11ea-91b6-66bbc810917b.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/muttering-moat/nonapole.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by SeekerNik** [comment]
I want to take this issue.
