### ISSUE TITLE
feat: Octapole

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1140]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/93038421-ea46a800-f67f-11ea-952d-3d813a43fafa.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/muttering-moat/octapole.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by SeekerNik** [comment]
I am interested in this issue.
