### ISSUE TITLE
feat: Hectic

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1142]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/93169806-e50d5a00-f760-11ea-83e9-dbb505dd0279.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/relay/hectic.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by mick4711** [comment]
I'd like to tackle this issue @TroyTae
