### ISSUE TITLE
feat: Metamorphosis II

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1143]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/93169945-33baf400-f761-11ea-9e9f-974847abd46d.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/life/oscillator/relay/metamorphosis-II.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by mick4711** [comment]
I'd like to tackle this issue @TroyTae

**Comment by okdd08** [comment]
Hey, i would like to do that.. :)
