### ISSUE TITLE
feat: Gourmet

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1144]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/93170163-9f9d5c80-f761-11ea-82e0-3dd771f61afd.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/shuttle/gourmet.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by mick4711** [comment]
I'd like to tackle this issue @TroyTae

**Comment by StijnLammers** [comment]
I'll take this one!
