### ISSUE TITLE
feat: Newshuttle

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1145]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/93170291-e4c18e80-f761-11ea-92f2-f387063bea62.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/life/oscillator/shuttle/newshuttle.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by okdd08** [comment]
Hey, i would like to do that.. :)
