### ISSUE TITLE
feat: Figure eight on 22P36

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1146]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/93170691-a4164500-f762-11ea-8007-be5fb5fefb86.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/figure-eight-on-22P36.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by StijnLammers** [comment]
I'll take this one!
