### ISSUE TITLE
feat: Figure eight on Jason's p22

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1148]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/93170986-33bbf380-f763-11ea-8407-7efa6b8e466e.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/life/oscillator/figure-eight-on-jasons-p22.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by smileLilith** [comment]
Hi, I can work on this one :smiley:
