### ISSUE TITLE
feat: Figure eight on pentadecathlon

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1149]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/93171128-75e53500-f763-11ea-8b0f-cc6a2eff29cf.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/figure-eight-on-pentadecathlon.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by mick4711** [comment]
I'd like to take this issue @TroyTae
