### ISSUE TITLE
feat: Figure eight on rattlesnake

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1150]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/93171227-a0cf8900-f763-11ea-83b8-fc1d2cb3905d.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/figure-eight-on-rattlesnake.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by jad837** [comment]
I would like to work on this.
