### ISSUE TITLE
feat: Figure eight

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1154]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/93301527-8c5ac180-f833-11ea-84bc-d41388142ba6.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/figure-eight.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by mick4711** [comment]
I'd like to tackle this issue @TroyTae
