### ISSUE TITLE
feat: Fire-spitting

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1155]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/93301680-c6c45e80-f833-11ea-9a3f-04d0812e7cbf.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/fire-spitting.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by The-Vector** [comment]
I'll have a go at this.
