### ISSUE TITLE
feat: Fountain

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1156]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/93302446-f758c800-f834-11ea-80b7-bb3d4efee96e.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/fountain.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by elishevaelbaz** [comment]
I'd like to tackle this issue @TroyTae
