### ISSUE TITLE
feat: Four eaters hassling four bookends

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1157]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/93303170-0c822680-f836-11ea-8678-ab744964295e.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/life/oscillator/four-eaters-hassling-four-bookends.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by duncanteege** [comment]
Hi there! I would like to pick this up :)
