### ISSUE TITLE
feat: Four eaters hassling lumps of muck

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1158]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/93303292-32a7c680-f836-11ea-90d0-aefcd40cbf16.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/four-eaters-hassling-lumps-of-muck.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by mattgw10** [comment]
I'd can add this pattern if it is still up for grabs.
