### ISSUE TITLE
feat: Cap and dock

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#116]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/66729397-1b25c800-ee86-11e9-9f89-087f2efb6b4b.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/cap-and-dock.ts

**Comment by spenc53** [comment]
I can take this one as well

**Comment by spenc53** [comment]
https://github.com/TroyTae/game-of-life/pull/139
