### ISSUE TITLE
feat: Fumarole on 34P14 shuttle

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1176]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/93600538-c629f480-f9fa-11ea-97d2-4fa2486b7f98.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/life/oscillator/fumarole-on-34P14-shuttle.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by smileLilith** [comment]
Hi, I can take this one :)
