### ISSUE TITLE
feat: Fumarole on Beluchenko's p13

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1178]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/93600889-51a38580-f9fb-11ea-9c64-696ca7a388e7.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/life/oscillator/fumarole-on-beluchenkos-p13.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by droidttk** [comment]
I'll work on this. Please assign this to me.

**Comment by jward8** [comment]
I can do this one
