### ISSUE TITLE
feat: Fumarole on p18 bi-block hassler

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1179]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/93601010-7ef03380-f9fb-11ea-8b2c-0711223f66ea.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/life/oscillator/fumarole-on-p18-bi-block-hassler.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by droidttk** [comment]
I'll work on this. Please assign this to me.

**Comment by okdd08** [comment]
Hey, i would like to do that.. :)
