### ISSUE TITLE
feat: Fumarole on Rich's p16

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1180]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/93601122-ac3ce180-f9fb-11ea-83cc-95b90f416857.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/life/oscillator/fumarole-on-richs-p16.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by droidttk** [comment]
I'll work on this. Please assign this to me.

**Comment by PushpikaWan** [comment]
can I work on this ?
