### ISSUE TITLE
feat: Fumarole on Rob's p16

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1181]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/93601207-ca0a4680-f9fb-11ea-874d-7a5157cc3d1c.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/fumarole-on-robs-p16.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by premkiran7** [comment]
I want to work on this @TroyTae

**Comment by TroyTae** [comment]
merged 93a269d
