### ISSUE TITLE
feat: Fumarole

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1182]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/93601272-e6a67e80-f9fb-11ea-9760-da31ee0e24ff.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/fumarole.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by AngelsProjects** [comment]
I want to help on this one
