### ISSUE TITLE
feat: Gabriel's p138

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1188]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/93849435-151ba680-fce7-11ea-8a61-114b69dfbee4.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/life/oscillator/gabriels-p138.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by TheIcySpark** [comment]
i want to work on this :)
