### ISSUE TITLE
feat: Glasses

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1189]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/93849503-409e9100-fce7-11ea-8aba-d2f74875b832.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/life/oscillator/glasses.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by AmrutaKoshe** [comment]
I would like to work on this!
