### ISSUE TITLE
feat: Harbor

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1190]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/93849655-8c513a80-fce7-11ea-97a2-245335cb44b9.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/life/oscillator/harbor.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by ahsanz024** [comment]
Hi,
I'd like to contribute to this.

**Comment by ahsanz024** [comment]
@TroyTae opened up a PR for this. Please review
https://github.com/TroyTae/game-of-life/pull/1207
