### ISSUE TITLE
feat: Heart

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1191]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/93849720-ae4abd00-fce7-11ea-8d05-0ec473b2878f.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/life/oscillator/heart.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by agit15** [comment]
Hey,

I would like to tackle this issue :)
