### ISSUE TITLE
feat: Heavyweight emulator

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1192]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/93849816-d89c7a80-fce7-11ea-89d2-e64029881721.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/life/oscillator/heavyweight-emulator.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by dinukad** [comment]
@TroyTae  I'm working on this. Please assign this to me.

**Comment by TroyTae** [comment]
@dinukad Please request another after finish one issue :)

**Comment by dinukad** [comment]
@TroyTae Created a PR for this https://github.com/TroyTae/game-of-life/pull/1221.
Please review and merge.
