### ISSUE TITLE
feat: Heavyweight volcano

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1193]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/93852146-75611700-fcec-11ea-981b-35c314b5e61c.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/life/oscillator/heavyweight-volcano.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by hawkril** [comment]
I'd like to do this, if it's still available.

**Comment by goodboi650** [comment]
Could I be assigned to this?

**Comment by TroyTae** [comment]
@goodboi650 
This issue is already assigned to @hawkril

**Comment by goodboi650** [comment]
Ah, duly noted, apologies. I'll wait for an unassigned issue to open up, then.
