### ISSUE TITLE
feat: Hebdarole

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1194]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/93852215-99245d00-fcec-11ea-89f8-9608adb76393.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/life/oscillator/hebdarole.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by dinukad** [comment]
@TroyTae  I'm working on this. Please assign this to me.

**Comment by ItsOKayCZ** [comment]
Hi, can I take this issue?
