### ISSUE TITLE
feat: Hive test tube baby

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1195]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/93852278-ba854900-fcec-11ea-8198-52d68476e0e2.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/life/oscillator/hive-test-tube-baby.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by dinukad** [comment]
@TroyTae  I'm working on this. Please assign this to me.

**Comment by koteswar375** [comment]
Hi,
Will work on this ..assign this to me

**Comment by premkiran7** [comment]
@TroyTae Can I work on this issue as I see that @koteswar375 has 2 issues already in his bucket.
