### ISSUE TITLE
feat: Honey thieves with test tube baby

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1196]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/93852451-033d0200-fced-11ea-81fd-c1d9451942ef.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/life/oscillator/honey-thieves-with-test-tube-baby.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by dinukad** [comment]
@TroyTae  I'm working on this. Please assign this to me.

**Comment by koteswar375** [comment]
Hi,
Assign this to me
