### ISSUE TITLE
feat: Honey thieves

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1197]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/93852686-70e92e00-fced-11ea-9e43-fa704b270c5b.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/life/oscillator/honey-thieves.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by PushpikaWan** [comment]
I would like to take this issue. Just for a confirmation, we need to create this pattern with 1,0 s that's all?

**Comment by TroyTae** [comment]
@PushpikaWan Yes that's all!
