### ISSUE TITLE
feat: Hook test tube baby

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1198]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/93852769-8d856600-fced-11ea-8cf2-a084def581f5.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/life/oscillator/hook-test-tube-baby.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by hannahcfalk** [comment]
hi, I'd like to help
