### ISSUE TITLE
feat: Hooks

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1199]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/93852863-c58ca900-fced-11ea-91c2-ea75f70fa03d.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/hooks.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by chaudhariyash10** [comment]
I want to try this. But I'm not sure what needs to be done. hooks.json file has a 3X3 matrix do we to transform it into the above-looking matrix and 0's for empty square and1's for black squares?

**Comment by TroyTae** [comment]
@chaudhariyash10 
Yes it is! 3x3 matrix is just a sample.

**Comment by chaudhariyash10** [comment]
Ok thanks. I'm working on this

**Comment by chaudhariyash10** [comment]
https://github.com/TroyTae/game-of-life/pull/1200#issue-490924840
Review this PR and suggest changes if any.
