### ISSUE TITLE
feat: Jack

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1203]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/94243277-23212f80-ff52-11ea-9aa4-2a47df57a42b.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/life/oscillator/jack.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by adrijere** [comment]
Hi! Can I take this one :) ?
