### ISSUE TITLE
feat: Jam

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1204]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/94243420-5499fb00-ff52-11ea-898b-f65152b01cab.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/life/oscillator/jam.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by ahsanz024** [comment]
@TroyTae fixed this one too.
Please take a look
https://github.com/TroyTae/game-of-life/pull/1208
