### ISSUE TITLE
feat: Jolson

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1220]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/94285950-5b932e80-ff8f-11ea-9467-157af49bd3b3.png)

Work at this [file](https://github.com/TroyTae/game-of-life/blob/master/life/oscillator/jolson.json) following [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md).  
If you leave comment, I'll assign to you!  
But please don't request too many issues at once :)

**Comment by manishprivet** [comment]
I want to work on this :smiley:
