### ISSUE TITLE
feat: Kok's galaxy

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1238]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/94516717-6389f180-0261-11eb-99d2-c22ec76b7412.png)

Work at this [file](https://github.com/TroyTae/game-of-life/blob/master/life/oscillator/koks-galaxy.json) following [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md).  
If you leave comment, I'll assign to you!  
But please don't request too many issues at once :)

**Comment by agrawal-deeksha** [comment]
I'll work on this. Please assign it to me.

**Comment by nitch193** [comment]
I this issue still open i want to work on this...
