### ISSUE TITLE
feat: Laputa

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1239]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/94516824-a946ba00-0261-11eb-94d4-b03a843ddb92.png)

Work at this [file](https://github.com/TroyTae/game-of-life/blob/master/life/oscillator/laputa.json) following [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md).  
If you leave comment, I'll assign to you!  
But please don't request too many issues at once :)

**Comment by DennisBoanini** [comment]
@TroyTae I want to work on this
