### ISSUE TITLE
feat: Lei

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1240]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/94516872-c2e80180-0261-11eb-8afc-439fba77cc97.png)

Work at this [file](https://github.com/TroyTae/game-of-life/blob/master/life/oscillator/lei.json) following [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md).  
If you leave comment, I'll assign to you!  
But please don't request too many issues at once :)

**Comment by DennisBoanini** [comment]
Can I work on this?
