### ISSUE TITLE
feat: Lightweight emulator

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1244]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/94517246-7c46d700-0262-11eb-9927-e47797f2aeb0.png)

Work at this [file](https://github.com/TroyTae/game-of-life/blob/master/life/oscillator/lightweight-emulator.json) following [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md).  
If you leave comment, I'll assign to you!  
But please don't request too many issues at once :)

**Comment by Ashwalls93** [comment]
@TroyTae  Please can i work on this? I can raise PR this evening.

**Comment by pyplacca** [comment]
I am open for this 🙋‍♂️
