### ISSUE TITLE
feat: Loaf test tube baby

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1245]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/94517281-941e5b00-0262-11eb-84ea-9d91a281ca55.png)

Work at this [file](https://github.com/TroyTae/game-of-life/blob/master/life/oscillator/loaf-test-tube-baby.json) following [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md).  
If you leave comment, I'll assign to you!  
But please don't request too many issues at once :)

**Comment by Ashwalls93** [comment]
I'd like to do this please - i can start later this evening

**Comment by pyplacca** [comment]
I'd like to resolve this issue if it's still open

**Comment by Thusal06** [comment]
I'd like to work on this!

**Comment by Thusal06** [comment]
@TroyTae Please, can you add the Hacktoberfest label to this issue, so it can be counted towards Hacktoberfest 2020.
