### ISSUE TITLE
feat: Loaflipflop

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1246]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/94517358-b912ce00-0262-11eb-81e0-66b1a8a7643b.png)

Work at this [file](https://github.com/TroyTae/game-of-life/blob/master/life/oscillator/loaflipflop.json) following [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md).  
If you leave comment, I'll assign to you!  
But please don't request too many issues at once :)

**Comment by DennisBoanini** [comment]
Can I try to resolve this issue?
