### ISSUE TITLE
feat: Mangled 1 beacon

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1251]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/94694051-6410ae00-036f-11eb-8bc0-eb022371d3a6.png)

Work at this [file](https://github.com/TroyTae/game-of-life/blob/master/life/oscillator/mangled-1-beacon.json) following [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md).  
If you leave comment, I'll assign to you!  
But please don't request too many issues at once :)

**Comment by kahkoii** [comment]
I would like to give this a shot!
