### ISSUE TITLE
feat: Mango test tube baby

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1252]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/94694189-86a2c700-036f-11eb-9cc4-1a4e696c1cb3.png)

Work at this [file](https://github.com/TroyTae/game-of-life/blob/master/life/oscillator/mango-test-tube-baby.json) following [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md).  
If you leave comment, I'll assign to you!  
But please don't request too many issues at once :)

**Comment by NitinNair89** [comment]
Hi,
I would like to work on this.

**Comment by diamondlee7** [comment]
@TroyTae Can you please assign me to this issue?

**Comment by wimanshaherath** [comment]
@TroyTae  I like to work on this issue. Can you assign this to me?

**Comment by TroyTae** [comment]
@wimanshaherath
This issue is already assigned to @diamondlee7
