### ISSUE TITLE
feat: Mazing

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1253]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/94694287-a4702c00-036f-11eb-9f4e-c35a74b30f61.png)

Work at this [file](https://github.com/TroyTae/game-of-life/blob/master/life/oscillator/mazing.json) following [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md).  
If you leave comment, I'll assign to you!  
But please don't request too many issues at once :)

**Comment by shamikakumar** [comment]
Hi, I'd like to tackle this!
