### ISSUE TITLE
feat: Middleweight emulator

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1257]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/94696952-92dc5380-0372-11eb-88fe-4094a806d186.png)

Work at this [file](https://github.com/TroyTae/game-of-life/blob/master/life/oscillator/middleweight-emulator.json) following [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md).  
If you leave comment, I'll assign to you!  
But please don't request too many issues at once :)

**Comment by NitinNair89** [comment]
Hi,
I would like to work on this.

**Comment by DennisBoanini** [comment]
Hi, I would like to work on this please
