### ISSUE TITLE
feat: Middleweight volcano

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1258]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/94697072-b7d0c680-0372-11eb-8bb4-aa187ac0f6af.png)

Work at this [file](https://github.com/TroyTae/game-of-life/blob/master/life/oscillator/middleweight-volcano.json) following [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md).  
If you leave comment, I'll assign to you!  
But please don't request too many issues at once :)

**Comment by bpedroza** [comment]
Can I take this one?

**Comment by bpedroza** [comment]
@TroyTae I can't run `npm run start` getting an error:
`UnhandledPromiseRejectionWarning: Error: Cannot find module '@mrmlnc/readdir-enhanced'`

Is there some additional setup step I missed?

**Comment by TroyTae** [comment]
Hmmm can you update your nodejs version?
Or remove `node_modules` directory and run `npm install` again.

**Comment by bpedroza** [comment]
Updated to most recent LTS version (12.8.4) deleted `node_modules` and ran `npm install` again.
Same issue. I'm on a windows machine, not sure if that matters.

**Comment by TroyTae** [comment]
![image](https://user-images.githubusercontent.com/20078201/94702820-287ae180-0379-11eb-8984-812382cfe380.png)
It's strange.. I'm also use windows machine.
And my version is `v12.18.3`. (I think `v12.8.4` can also run code)
Can you capture your full error message?

**Comment by bpedroza** [comment]
Sure:

```
> @ start C:\inetpub\wwwroot\game-of-life
> parcel src/index.html --open

(node:3796) UnhandledPromiseRejectionWarning: Error: Cannot find module '@mrmlnc/readdir-enhanced'
Require stack:
- C:\inetpub\wwwroot\game-of-life\node_modules\parcel-bundler\node_modules\fast-glob\out\providers\reader-async.js
- C:\inetpub\wwwroot\game-of-life\node_modules\parcel-bundler\node_modules\fast-glob\out\index.js
- C:\inetpub\wwwroot\game-of-life\node_modules\parcel-bundler\node_modules\fast-glob\index.js
- C:\inetpub\wwwroot\game-of-life\node_modules\parcel-bundler\src\utils\glob.js
- C:\inetpub\wwwroot\game-of-life\node_modules\parcel-bundler\src\Resolver.js
- C:\inetpub\wwwroot\game-of-life\node_modules\parcel-bundler\src\Bundler.js
- C:\inetpub\wwwroot\game-of-life\node_modules\parcel-bundler\index.js
- C:\inetpub\wwwroot\game-of-life\node_modules\parcel-bundler\src\cli.js
- C:\inetpub\wwwroot\game-of-life\node_modules\parcel-bundler\bin\cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (C:\inetpub\wwwroot\game-of-life\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at Object.<anonymous> (C:\inetpub\wwwroot\game-of-life\node_modules\parcel-bundler\node_modules\fast-glob\out\providers\reader-async.js:16:15)
    at Module._compile (C:\inetpub\wwwroot\game-of-life\node_modules\v8-compile-cache\v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
(node:3796) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3796) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by bpedroza** [comment]
Maybe you can check your `package-lock.json` file so we can ensure all packages are the same version when running `npm install` to eliminate a possible issue with different versions of packages?

**Comment by bpedroza** [comment]
Got it working on a different computer not sure what the problem was.

**Comment by onbitSyn** [comment]
I want to work on this issue. Can you assign it to me.

**Comment by TroyTae** [comment]
closed by 64433616300ebc0bc22e9346e12cc416594131d1

**Comment by bpedroza** [comment]
@onbitSyn  @TroyTae I had started on this already. Spent a couple hours trying to figure out why it wasn't working and you assign to someone else. Not cool.

**Comment by TroyTae** [comment]
@bpedroza 
I apologize but I didn't assign this to anyone.
And the commit isn't created by @onbitSyn 
`fsociety343` creates PR without comment.
Anyway I understand what's your feeling. I'm so sorry.

**Comment by bpedroza** [comment]
My apologies @onbitSyn then. And thanks for commenting.
