### ISSUE TITLE
Revamp website UI

### ISSUE THREAD

**Issue by NitinNair89** [TroyTae/game-of-life#1259]
I was thinking whether we can revamp the overall UI for this website. Maybe something similar to Codepen.io would be cool to have, no?

If the landing page is divided into "sections" and each section is further divided into "Cards" then each element can reside in the card. The card can have more details like when it was created, purpose of element, etc.

For example, "1 beacon" will have its own card, and that card would show details like:
- Name
- Purpose

Thoughts?

**Comment by TroyTae** [comment]
There is a duplicate issue.
Can you discuss in #1055 about this?
