### ISSUE TITLE
feat: Mold on 34P14 shuttle

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1292]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/94983512-5d0bba80-057e-11eb-99e0-5f80bd6ac969.png)

Work at this [file](https://github.com/TroyTae/game-of-life/blob/master/life/oscillator/mold-on-34P14-shuttle.json) following [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md).  
If you leave comment, I'll assign to you!  
But please don't request too many issues at once :)

**Comment by vsushruth** [comment]
I would like to work on this

**Comment by TroyTae** [comment]
Please request another one after finish one :)

**Comment by pyplacca** [comment]
I would like to take it up if help is still needed.
