### ISSUE TITLE
feat: Mold on 41P7.2

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1293]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/94983534-9ba17500-057e-11eb-8e33-8e56a59ba560.png)

Work at this [file](https://github.com/TroyTae/game-of-life/blob/master/life/oscillator/mold-on-41P7_2.json) following [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md).  
If you leave comment, I'll assign to you!  
But please don't request too many issues at once :)

**Comment by SutharMukesh** [comment]
looks interesting, can i take this one?
