### ISSUE TITLE
feat: Mold on fumarole

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1294]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/94983563-e3c09780-057e-11eb-9fd8-af0ab737fe6c.png)

Work at this [file](https://github.com/TroyTae/game-of-life/blob/master/life/oscillator/mold-on-fumarole.json) following [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md).  
If you leave comment, I'll assign to you!  
But please don't request too many issues at once :)

**Comment by vsushruth** [comment]
I would like to work on this

**Comment by manishita24** [comment]
I'll work on this.

**Comment by manishita24** [comment]
my pr always fails prettier test I don't know why. it gives me this error "Code style issues found in the above file(s). Forgot to run Prettier?"

what should I do?

**Comment by dinukad** [comment]
@manishita24 seems it is an indentation issue. please follow original indentation.

**Comment by pyplacca** [comment]
I could take it up if you want @manishita24

**Comment by manishita24** [comment]
@TroyTae done. Please review.

**Comment by manishita24** [comment]
> @manishita24 seems it is an indentation issue. please follow original indentation.

yes. I finally figured out about prettier extension. Thanks
