### ISSUE TITLE
feat: Mold on Jason's p22

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1295]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/94983575-03f05680-057f-11eb-9b2b-6fd2ffce6913.png)

Work at this [file](https://github.com/TroyTae/game-of-life/blob/master/life/oscillator/mold-on-jasons-p22.json) following [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md).  
If you leave comment, I'll assign to you!  
But please don't request too many issues at once :)

**Comment by ry-v1** [comment]
@TroyTae  - I can work on this, Can you please assign.
