### ISSUE TITLE
feat: Mold on long hook eating tub

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1296]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/94983587-2edaaa80-057f-11eb-844b-f231556feadb.png)

Work at this [file](https://github.com/TroyTae/game-of-life/blob/master/life/oscillator/mold-on-long-hook-eating-tub.json) following [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md).  
If you leave comment, I'll assign to you!  
But please don't request too many issues at once :)

**Comment by vsushruth** [comment]
I would like to work on this

**Comment by agrawal-deeksha** [comment]
Hi! I would love to work on this. Please assign it to me.
