### ISSUE TITLE
feat: Mold on Merzenich's p31

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1297]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/94983598-516cc380-057f-11eb-91b7-cf92b3235c4a.png)

Work at this [file](https://github.com/TroyTae/game-of-life/blob/master/life/oscillator/mold-on-merzenichs-p31.json) following [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md).  
If you leave comment, I'll assign to you!  
But please don't request too many issues at once :)

**Comment by vsushruth** [comment]
I would like to work on this

**Comment by bindu-r02** [comment]
@TroyTae - Can you assign to me
