### ISSUE TITLE
feat: Mold on pentadecathlon

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1298]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/94983611-6ba6a180-057f-11eb-9523-b9b5d2cdb1ac.png)

Work at this [file](https://github.com/TroyTae/game-of-life/blob/master/life/oscillator/mold-on-pentadecathlon.json) following [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md).  
If you leave comment, I'll assign to you!  
But please don't request too many issues at once :)

**Comment by PushpikaWan** [comment]
can I work on this.
