### ISSUE TITLE
feat: Mold on rattlesnake

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1299]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/94983626-909b1480-057f-11eb-8ad9-84212e6f79bc.png)

Work at this [file](https://github.com/TroyTae/game-of-life/blob/master/life/oscillator/mold-on-rattlesnake.json) following [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md).  
If you leave comment, I'll assign to you!  
But please don't request too many issues at once :)

**Comment by okdd08** [comment]
Hey, i would like to do that :)

**Comment by TroyTae** [comment]
Please request another one after finish one :)

**Comment by okdd08** [comment]
okay, thanks :)

**Comment by MKPATH2015** [comment]
Hey, Can I take it up? :)
