### ISSUE TITLE
feat: Carrier siamese very long snake

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#130]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/66730828-f2ee9700-ee8e-11e9-8a6b-6b1d7c801b3c.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/carrier-siamese-very-long-snake.ts

**Comment by TroyTae** [comment]
d

**Comment by lakkuma1989** [comment]
please, review PR https://github.com/TroyTae/game-of-life/pull/144

**Comment by TroyTae** [comment]
d
