### ISSUE TITLE
feat: Mold

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1300]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/94983646-bfb18600-057f-11eb-9f4d-14b1e7c3add7.png)

Work at this [file](https://github.com/TroyTae/game-of-life/blob/master/life/oscillator/mold.json) following [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md).  
If you leave comment, I'll assign to you!  
But please don't request too many issues at once :)

**Comment by okdd08** [comment]
Hey, i would like to do that :)
