### ISSUE TITLE
feat: Carrier tie boat

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#131]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/66730859-26312600-ee8f-11e9-9fb9-810df2c5b6b6.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/carrier-tie-boat.ts

**Comment by TroyTae** [comment]
d

**Comment by rakithasiriwardana** [comment]
@TroyTae I will work on this

**Comment by lakkuma1989** [comment]
please, review PR https://github.com/TroyTae/game-of-life/pull/143 for this
