### ISSUE TITLE
feat: Fumarole on Achim's p11

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1312]
Let's make this pattern:
![93600755-1ef98d00-f9fb-11ea-99af-39479597ef9e](https://user-images.githubusercontent.com/20078201/95040805-bf47f500-070f-11eb-990e-ab141818c28a.png)

Work at this [file](https://github.com/TroyTae/game-of-life/blob/master/life/oscillator/fumarole-on-achims-p11.json) following [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md).  
If you leave comment, I'll assign to you!  
But please don't request too many issues at once :)

**Comment by farayolaj** [comment]
Hello, can I work on this?
