### ISSUE TITLE
feat: Figure eight on Beluchenko's p13

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1313]
Let's make this pattern:
![93170837-f0618500-f762-11ea-9357-bd1621eec829](https://user-images.githubusercontent.com/20078201/95040838-e1da0e00-070f-11eb-82b1-98397a8c0710.png)

Work at this [file](https://github.com/TroyTae/game-of-life/blob/master/life/oscillator/figure-eight-on-beluchenkos-p13.json) following [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md).  
If you leave comment, I'll assign to you!  
But please don't request too many issues at once :)

**Comment by tomasloksa** [comment]
Hey, I'd liek to work on this.
