### ISSUE TITLE
feat: Monoclaw test tube baby

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1314]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/95040947-439a7800-0710-11eb-9e0d-9c6bbbb2fd37.png)

Work at this [file](https://github.com/TroyTae/game-of-life/blob/master/life/oscillator/monoclaw-test-tube-baby.json) following [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md).  
If you leave comment, I'll assign to you!  
But please don't request too many issues at once :)

**Comment by vsushruth** [comment]
I would like to work on this
