### ISSUE TITLE
feat: Monogram

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1315]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/95040997-69278180-0710-11eb-8171-25d1c6d47b24.png)

Work at this [file](https://github.com/TroyTae/game-of-life/blob/master/life/oscillator/monogram.json) following [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md).  
If you leave comment, I'll assign to you!  
But please don't request too many issues at once :)

**Comment by dinukad** [comment]
@TroyTae I like to work on this issue; can you please assign this to me.
