### ISSUE TITLE
feat: Montana

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1316]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/95041062-970cc600-0710-11eb-8a62-4cc28744ddec.png)

Work at this [file](https://github.com/TroyTae/game-of-life/blob/master/life/oscillator/montana.json) following [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md).  
If you leave comment, I'll assign to you!  
But please don't request too many issues at once :)

**Comment by vsushruth** [comment]
I would like to work on this too. 
I have already created a PR for the last issue I was assigned :)

**Comment by TroyTae** [comment]
closed by #1318
