### ISSUE TITLE
feat: Carrier tie ship

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#132]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/66730876-4234c780-ee8f-11e9-9f28-23e5c0fa2bd5.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/carrier-tie-ship.ts

**Comment by TroyTae** [comment]
d

**Comment by spenc53** [comment]
https://github.com/TroyTae/game-of-life/pull/138
