### ISSUE TITLE
feat: Octagon 4

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1322]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/95206337-8c8e2180-0821-11eb-88d8-099358e91fb8.png)

Work at this [file](https://github.com/TroyTae/game-of-life/blob/master/life/oscillator/octagon-4.json) following [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md).  
If you leave comment, I'll assign to you!  
But please don't request too many issues at once :)

**Comment by Tshintuu** [comment]
Hi @TroyTae ! I would like to work on this issue if possible. :)
