### ISSUE TITLE
feat: Odd keys

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1323]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/95206475-b5aeb200-0821-11eb-93db-c2910c23309d.png)

Work at this [file](https://github.com/TroyTae/game-of-life/blob/master/life/oscillator/odd-keys.json) following [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md).  
If you leave comment, I'll assign to you!  
But please don't request too many issues at once :)

**Comment by preethi900** [comment]
I would like to work on this issue!!!

**Comment by preethi900** [comment]
If u are fine with fix can you can add the hacktoberfest-accepted tag to this PR??
