### ISSUE TITLE
feat: Odd test tube baby

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1324]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/95206659-eb539b00-0821-11eb-944e-ae113cae11e4.png)

Work at this [file](https://github.com/TroyTae/game-of-life/blob/master/life/oscillator/odd-test-tube-baby.json) following [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md).  
If you leave comment, I'll assign to you!  
But please don't request too many issues at once :)

**Comment by okdd08** [comment]
hey, can i do this one?
