### ISSUE TITLE
feat: Overweight emulator

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1325]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/95206805-163def00-0822-11eb-8055-372db44e94d1.png)

Work at this [file](https://github.com/TroyTae/game-of-life/blob/master/life/oscillator/overweight-emulator.json) following [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md).  
If you leave comment, I'll assign to you!  
But please don't request too many issues at once :)

**Comment by silltho** [comment]
i would like to work on this.

**Comment by MoulinLouis** [comment]
@silltho you have one comma that is not needed in your code

**Comment by silltho** [comment]
good point. I added an additional commit.
