### ISSUE TITLE
feat: Carrier with feather

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#133]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/66730906-6d1f1b80-ee8f-11e9-8e0e-1d00c519511e.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/carrier-with-feather.ts

**Comment by droidttk** [comment]
Let me work on this. please assign this to me.

**Comment by droidttk** [comment]
Created a PR #159. Please review and merge.
