### ISSUE TITLE
feat: Century eater

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#134]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/66730931-8aec8080-ee8f-11e9-9e0a-2434134081a8.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/eater/century-eater.ts

**Comment by droidttk** [comment]
Let me work on this. please assign this to me.

**Comment by droidttk** [comment]
Created a PR: #158 Pleaser review and merge
