### ISSUE TITLE
feat: P10 traffic light hassler

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1349]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/97864183-8a00e800-1d4b-11eb-8426-8646654feb41.png)

Work at this [file](https://github.com/TroyTae/game-of-life/blob/main/life/oscillator/p10-traffic-light-hassler.json) following [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md).  
If you leave comment, I'll assign to you!  
But please don't request too many issues at once :)

**Comment by wafuwafu13** [comment]
@TroyTae Could I try this one?
