### ISSUE TITLE
feat: P11 double-length signal injector

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1350]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/97864307-bb79b380-1d4b-11eb-92a4-bc7f43bddcfe.png)

Work at this [file](https://github.com/TroyTae/game-of-life/blob/main/life/oscillator/p11-double-length-signal-injector.json) following [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md).  
If you leave comment, I'll assign to you!  
But please don't request too many issues at once :)

**Comment by pyplacca** [comment]
I'll take this one as well
