### ISSUE TITLE
feat: P11 pinwheel

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1351]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/97866378-2b3d6d80-1d4f-11eb-9bed-1cea92923ffe.png)

Work at this [file](https://github.com/TroyTae/game-of-life/blob/main/life/oscillator/p11-pinwheel.json) following [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md).  
If you leave comment, I'll assign to you!  
But please don't request too many issues at once :)

**Comment by stabee** [comment]
@TroyTae Could I try this one?
