### ISSUE TITLE
feat: P124 lumps of muck hassler

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1353]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/97868063-62614e00-1d52-11eb-9375-c89a3d8c8a92.png)

Work at this [file](https://github.com/TroyTae/game-of-life/blob/main/life/oscillator/p124-lumps-of-muck-hassler.json) following [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md).  
If you leave comment, I'll assign to you!  
But please don't request too many issues at once :)

**Comment by pyplacca** [comment]
I'd like to take this up please
