### ISSUE TITLE
feat: P18 honey farm hassler

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1358]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/98112948-4989a180-1ee6-11eb-9f1c-d5f009b142e4.png)

Work at this [file](https://github.com/TroyTae/game-of-life/blob/main/life/oscillator/p18-honey-farm-hassler.json) following [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md).  
If you leave comment, I'll assign to you!  
But please don't request too many issues at once :)

**Comment by phileasthefogg** [comment]
I'll give it a shot!
