### ISSUE TITLE
feat: P22 lumps of muck hassler

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1364]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/98676731-52271f80-239f-11eb-8ff3-618ab1a907a4.png)

Work at this [file](https://github.com/TroyTae/game-of-life/blob/main/life/oscillator/p22-lumps-of-muck-hassler.json) following [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md).  
If you leave comment, I'll assign to you!  
But please don't request too many issues at once :)

**Comment by Syntax3rr** [comment]
I'll take it if you wouldn't mind.
