### ISSUE TITLE
feat: P29 pentadecathlon hassler

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1365]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/98676865-84d11800-239f-11eb-9202-3776367ae899.png)

Work at this [file](https://github.com/TroyTae/game-of-life/blob/main/life/oscillator/p29-pentadecathlon-hassler.json) following [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md).  
If you leave comment, I'll assign to you!  
But please don't request too many issues at once :)

**Comment by dominguetigs** [comment]
Assign me as well @TroyTae :-)
