### ISSUE TITLE
feat: P29 traffic-farm hassler

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1368]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/98813194-27a09980-2467-11eb-9a12-52a0d40f80f8.png)

Work at this [file](https://github.com/TroyTae/game-of-life/blob/main/life/oscillator/p29-traffic-farm-hassler.json) following [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md).  
If you leave comment, I'll assign to you!  
But please don't request too many issues at once :)

**Comment by zg3d** [comment]
can I do this issue
