### ISSUE TITLE
feat: P32 blinker hassler 2

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1369]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/98813396-6e8e8f00-2467-11eb-884b-16ab771e7636.png)

Work at this [file](https://github.com/TroyTae/game-of-life/blob/main/life/oscillator/p32-blinker-hassler-2.json) following [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md).  
If you leave comment, I'll assign to you!  
But please don't request too many issues at once :)

**Comment by mmosru** [comment]
Please assign this issue to me. Thanks!
