### ISSUE TITLE
feat: P32 blinker hassler

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1370]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/98813501-9aaa1000-2467-11eb-8c8d-dd175d3064e1.png)

Work at this [file](https://github.com/TroyTae/game-of-life/blob/main/life/oscillator/p32-blinker-hassler.json) following [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md).  
If you leave comment, I'll assign to you!  
But please don't request too many issues at once :)

**Comment by Google987** [comment]
Hi,
I want to take this up.

**Comment by mmosru** [comment]
To test mine, I printed the pattern image, and also printed my 0s and 1s json array, and used a marker to draw squares over the ones.

**Comment by Google987** [comment]
![image](https://user-images.githubusercontent.com/30652896/99896331-9e366600-2cb5-11eb-88a2-89c2e8fcc2c6.png)
Here is the output.

PR: https://github.com/TroyTae/game-of-life/pull/1379

Please let me know if there's anything wrong with this pr.

**Comment by Google987** [comment]
> To test mine, I printed the pattern image, and also printed my 0s and 1s json array, and used a marker to draw squares over the ones.
![image](https://user-images.githubusercontent.com/30652896/99896550-8eb81c80-2cb7-11eb-9ff2-724c28c6ec0d.png)

i added this line 27 {engine.stopLife();} to stop the pattern. it worked for me.
