### ISSUE TITLE
feat: P35 beehive hassler

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1371]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/98955221-fd6fda00-2541-11eb-9441-af966f6aa4a8.png)

Work at this [file](https://github.com/TroyTae/game-of-life/blob/main/life/oscillator/p35-beehive-hassler.json) following [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md).  
If you leave comment, I'll assign to you!  
But please don't request too many issues at once :)

**Comment by leopoldwe** [comment]
Can I be assigned this issue?
