### ISSUE TITLE
feat: P35 honey farm hassler

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1372]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/98955406-2d1ee200-2542-11eb-8ce0-a542b10b087a.png)

Work at this [file](https://github.com/TroyTae/game-of-life/blob/main/life/oscillator/p35-honey-farm-hassler.json) following [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md).  
If you leave comment, I'll assign to you!  
But please don't request too many issues at once :)

**Comment by aabacchus** [comment]
@TroyTae Can I have a go? This'll be my first contribution and I'm excited!
