### ISSUE TITLE
feat: P36 toad hassler

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1373]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/98955599-6eaf8d00-2542-11eb-9544-ad3ab7b63497.png)

Work at this [file](https://github.com/TroyTae/game-of-life/blob/main/life/oscillator/p36-toad-hassler.json) following [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md).  
If you leave comment, I'll assign to you!  
But please don't request too many issues at once :)

**Comment by dominguetigs** [comment]
I`d like to assign to me :-)
