### ISSUE TITLE
feat: Pinwheel

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1381]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/100497370-7015c200-319e-11eb-96cc-84b0963a85fb.png)

Work at this [file](https://github.com/TroyTae/game-of-life/blob/main/life/oscillator/billiard-table/pinwheel.json) following [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md).  
If you leave comment, I'll assign to you!  
But please don't request too many issues at once :)

**Comment by pyplacca** [comment]
👋

**Comment by bryanyng** [comment]
I'll work on this! It will be my first contribution :)
