### ISSUE TITLE
feat: Pressure cooker

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1382]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/100497390-a2bfba80-319e-11eb-826a-48d37d2bb067.png)

Work at this [file](https://github.com/TroyTae/game-of-life/blob/main/life/oscillator/billiard-table/pressure-cooker.json) following [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md).  
If you leave comment, I'll assign to you!  
But please don't request too many issues at once :)

**Comment by pyplacca** [comment]
👋

**Comment by tlightk** [comment]
I'd like to work on this pattern, please!
