### ISSUE TITLE
feat: Protein

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1383]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/100497414-d569b300-319e-11eb-9372-da4a4085bbfd.png)

Work at this [file](https://github.com/TroyTae/game-of-life/blob/main/life/oscillator/billiard-table/protein.json) following [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md).  
If you leave comment, I'll assign to you!  
But please don't request too many issues at once :)

**Comment by pyplacca** [comment]
👋

**Comment by TroyTae** [comment]
@pyplacca Please complete `P110 traffic jam`

**Comment by the-mgi** [comment]
I would like to work if you can brief me a bit about what to make specifically, coz i am un aware of this game

**Comment by TroyTae** [comment]
@the-mgi 
Do you read this guide(https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md)?
Which step makes you confused?
