### ISSUE TITLE
feat: Pentapole

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1385]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/100612370-3a1b3e00-3356-11eb-8d57-e0ea44557ef1.png)

Work at this [file](https://github.com/TroyTae/game-of-life/blob/main/life/oscillator/muttering-moat/pentapole.json) following [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md).  
If you leave comment, I'll assign to you!  
But please don't request too many issues at once :)

**Comment by sgayangi** [comment]
Hi, could I work on this? I've never contributed before so I would like to try :)
