### ISSUE TITLE
feat: Phoenix 1

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1390]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/102716700-de265280-4320-11eb-816f-0d1b87b81e4a.png)

Work at this [file](https://github.com/TroyTae/game-of-life/blob/main/life/oscillator/phoenix/phoenix-1.json) following [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md).  
If you leave comment, I'll assign to you!  
But please don't request too many issues at once :)

**Comment by tirlochanarora16** [comment]
Hey, I'd love to work on this but I have some questions about it.

**Comment by tirlochanarora16** [comment]
In the `phoenix-1.json` file the `life` array has to be modified with 0 and 1 following the pattern in the image, right?
