### ISSUE TITLE
feat: P43 Snark loop

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1392]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/102716783-5e4cb800-4321-11eb-9244-96957d50abff.png)

Work at this [file](https://github.com/TroyTae/game-of-life/blob/main/life/oscillator/relay/p43-snark-loop.json) following [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md).  
If you leave comment, I'll assign to you!  
But please don't request too many issues at once :)

**Comment by 30james00** [comment]
I can do this
