### ISSUE TITLE
feat: P49 bumper loop

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1393]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/102716818-8b00cf80-4321-11eb-9d35-f7db55820838.png)

Work at this [file](https://github.com/TroyTae/game-of-life/blob/main/life/oscillator/relay/p49-bumper-loop.json) following [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md).  
If you leave comment, I'll assign to you!  
But please don't request too many issues at once :)

**Comment by devansh5** [comment]
I'd like to work on this.
