### ISSUE TITLE
feat: p5 pipsquirter

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1410]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/135647733-f3c65786-6fea-4617-b503-5fdcd8cec200.png)

Work at this [file](https://github.com/TroyTae/game-of-life/blob/main/docs/patterns/oscillator/p5-pipsquirter.json) following [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md).  
If you leave comment, I'll assign to you!  
But please don't request too many issues at once :)

**Comment by themonster2015** [comment]
I'd like to work on this.
