### ISSUE TITLE
feat: p55 pre-pulsar hassler

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1412]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/135648232-24f1ea21-e5c4-4de3-9b0e-a8bdc6f4b93a.png)

Work at this [file](https://github.com/TroyTae/game-of-life/blob/main/docs/patterns/oscillator/p55-pre-pulsar-hassler.json) following [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md).  
If you leave comment, I'll assign to you!  
But please don't request too many issues at once :)

**Comment by Aniket-508** [comment]
@TroyTae Can I take up this issue?

**Comment by Aniket-508** [comment]
@TroyTae Pls review my PR!
