### ISSUE TITLE
feat: p58 toadsucker

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1413]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/135648615-c9ebd215-35b6-49f7-bbcd-5f8b2025b400.png)

Work at this [file](https://github.com/TroyTae/game-of-life/blob/main/docs/patterns/oscillator/p58-toadsucker.json) following [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md).  
If you leave comment, I'll assign to you!  
But please don't request too many issues at once :)

**Comment by chrismilson** [comment]
I'm interested in this!

**Comment by BlueGhost12** [comment]
Hello! I'm interested in this!

**Comment by TroyTae** [comment]
@BlueGhost12 This isssue is already assigned to @chrismilson
