### ISSUE TITLE
feat: p6 thumb

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1415]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/135650690-0b6687ca-db76-4a6b-9cdc-bfe6ddab2746.png)

Work at this [file](https://github.com/TroyTae/game-of-life/blob/main/docs/patterns/oscillator/p6-thumb.json) following [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md).  
If you leave comment, I'll assign to you!  
But please don't request too many issues at once :)

**Comment by a-rokay** [comment]
I'd like to work on this!
