### ISSUE TITLE
feat: p60 B-heptomino hassler

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1416]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/135650866-a20ea8a8-7fd8-44f9-b8dc-24e5bb25a750.png)

Work at this [file](https://github.com/TroyTae/game-of-life/blob/main/docs/patterns/oscillator/p60-b-heptomino-hassler.json) following [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md).  
If you leave comment, I'll assign to you!  
But please don't request too many issues at once :)

**Comment by mariothedog** [comment]
Hi, I'd like to work on this :]
