### ISSUE TITLE
feat: p60 traffic light hassler

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1417]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/135651050-548e618e-3c43-4354-b162-57a681ce9b59.png)

Work at this [file](https://github.com/TroyTae/game-of-life/blob/main/docs/patterns/oscillator/p60-traffic-light-hassler.json) following [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md).  
If you leave comment, I'll assign to you!  
But please don't request too many issues at once :)

**Comment by thevibhu** [comment]
I would like to work on this issue!

**Comment by thevibhu** [comment]
@TroyTae could you please review this PR https://github.com/TroyTae/game-of-life/pull/1421 ?
