### ISSUE TITLE
feat: P64 thunderbird hassler

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1431]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/141886793-1bf30f3b-038e-4b97-93d9-4105129a67af.png)

Work at this [file](https://github.com/TroyTae/game-of-life/blob/main/docs/patterns/oscillator/p64-thunderbird-hassler.json) following [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md).  
If you leave comment, I'll assign to you!  
But please don't request too many issues at once :)

**Comment by SaiKiranMukka** [comment]
I would like to work on this issue!
