### ISSUE TITLE
feat: P72 quasi-shuttle

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1432]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/141886952-3965d27a-2f54-491e-b791-cdf4903fa354.png)

Work at this [file](https://github.com/TroyTae/game-of-life/blob/main/docs/patterns/oscillator/p72-quasi-shuttle.json) following [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md).  
If you leave comment, I'll assign to you!  
But please don't request too many issues at once :)

**Comment by SaiKiranMukka** [comment]
I would like to work on this issue!
