### ISSUE TITLE
feat: Pedestle

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1433]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/141887084-e61ea6ac-14a5-445a-bdeb-cb50e9749a85.png)

Work at this [file](https://github.com/TroyTae/game-of-life/blob/main/docs/patterns/oscillator/pedestle.json) following [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md).  
If you leave comment, I'll assign to you!  
But please don't request too many issues at once :)

**Comment by cimbraien** [comment]
Can you assign this issue to me? Thanks!
