### ISSUE TITLE
feat: Penny lane

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#1434]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/141887505-916b3929-6fcf-4273-ab9e-29bdc22e1c77.png)

Work at this [file](https://github.com/TroyTae/game-of-life/blob/main/docs/patterns/oscillator/penny-lane.json) following [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md).  
If you leave comment, I'll assign to you!  
But please don't request too many issues at once :)

**Comment by HritikR** [comment]
Hi Troy, can you assign this to me.
