### ISSUE TITLE
feat: sword

### ISSUE THREAD

**Issue by ramyashreeshetty** [TroyTae/game-of-life#1442]
Let's make this pattern:

https://cdn.discordapp.com/attachments/801749884641607692/1018485305210314764/unknown.png

**Comment by TroyTae** [comment]
Hello thank you for submtting issue and PR!
But it seems this pattern isn't work.
Can I ask type of this pattern?

**Comment by ramyashreeshetty** [comment]
![image](https://user-images.githubusercontent.com/43513353/189530876-a73c4999-0c24-4771-b25e-5cc0bb67ca45.png)

**Comment by ramyashreeshetty** [comment]
i have already add this feature into the code, waiting for your review

**Comment by TroyTae** [comment]
Yes I already saw that but it doesn't work as oscillator pattern.
Did you test this pattern?

**Comment by ramyashreeshetty** [comment]
oh! I'm sorry could you explain the difference between all these patterns

**Comment by TroyTae** [comment]
Sure you can read about that at here:
https://en.wikipedia.org/wiki/Conway%27s_Game_of_Life#Examples_of_patterns

**Comment by ramyashreeshetty** [comment]
okay after reading this I understood this properly!!! also, I m really fascinated thanks for the info. I'll create a new issue
