### ISSUE TITLE
feat: Claw with boat with tail

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#152]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/66797669-82a34c80-ef46-11e9-9baa-03857c48a545.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/claw-with-boat-with-tail.ts

**Comment by Thilagavathi1** [comment]
@TroyTae  Raised [PR](https://github.com/TroyTae/game-of-life/pull/200). Please check it.

**Comment by Thilagavathi1** [comment]
@TroyTae Raise [PR](https://github.com/TroyTae/game-of-life/pull/20) Please check it.
