### ISSUE TITLE
feat: Claw with tail

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#153]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/66797702-a8c8ec80-ef46-11e9-8c25-a054cddb546b.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/claw-with-tail.ts

**Comment by hasalassh** [comment]
@TroyTae Let me work on this...!
