### ISSUE TITLE
feat: Cloverleaf interchange

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#156]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/66797868-21c84400-ef47-11e9-940f-6e56674e2188.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/cloverleaf-interchange.ts

**Comment by Thilagavathi1** [comment]
@TroyTae  wanna work on this

**Comment by TroyTae** [comment]
@Thilagavathi1 
I assigned you this issue.
Thank you for your interest!

**Comment by Thilagavathi1** [comment]
Raised [PR](https://github.com/TroyTae/game-of-life/pull/162/commits/5438cb0e8678b5e88c2908651c42ac1c261a1737) Please check this and let me know
