### ISSUE TITLE
feat: Cthulhu

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#157]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/66797909-3dcbe580-ef47-11e9-9dcf-d3c405b40e5e.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/cthulhu.ts

**Comment by Thilagavathi1** [comment]
@TroyTae Shall i work on this ?

**Comment by TroyTae** [comment]
@Thilagavathi1 Sure!

**Comment by Thilagavathi1** [comment]
@TroyTae Raised [PR](https://github.com/TroyTae/game-of-life/pull/163/commits/aa2b6911b015c736804170c0480d9ef1c7e2df8a) Please check this.
