### ISSUE TITLE
feat: Cis-block on long hook

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#167]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/66809422-4c76c480-ef68-11e9-87c2-f10e67e8a12e.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/cis-block-on-long-hook.ts

**Comment by Jam-Iko** [comment]
Hi, I would like to do this task. Can you please assign this issue to me? Thanks!
