### ISSUE TITLE
feat: Cis-boat amphisbaena

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#168]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/66809488-687a6600-ef68-11e9-8e00-325745a80332.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/cis-boat-amphisbaena.ts

**Comment by madmaxWMFU** [comment]
Hi @TroyTae , I would love to help to create this template. Can I?
