### ISSUE TITLE
feat: Cis-boat line tub

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#170]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/66809589-9e1f4f00-ef68-11e9-88c6-fff667d1d4b1.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/cis-boat-line-tub.ts

**Comment by madmaxWMFU** [comment]
Hi @TroyTae , I would love to help to create this template. Can I?
