### ISSUE TITLE
feat: Cis-boat on dock

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#171]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/66809640-b7c09680-ef68-11e9-98d7-cf2f48bf05da.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/cis-boat-on-dock.ts

**Comment by madmaxWMFU** [comment]
Hi @TroyTae , I would love to help to create this template. Can I?

**Comment by TroyTae** [comment]
closed by #214
