### ISSUE TITLE
feat: Cis-carrier up on table

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#177]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/66810206-b80d6180-ef69-11e9-8280-ecfee1a5c9b2.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/cis-carrier-up-on-table.ts

**Comment by nazmariam** [comment]
Hi! Could I do this one please?
