### ISSUE TITLE
feat: Add Storke On Background

### ISSUE THREAD

**Issue by kwangkuk0821** [TroyTae/game-of-life#18]
## Before
![image](https://user-images.githubusercontent.com/9026105/66380144-c56a9f00-e9f1-11e9-9d1a-e6535e3ba818.png)

## After
![image](https://user-images.githubusercontent.com/9026105/66380210-ec28d580-e9f1-11e9-9d89-6e7f30eeb75f.png)

**Comment by TroyTae** [comment]
closed by #19
