### ISSUE TITLE
feat: Cis-hook and R-bee

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#180]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/66810341-0ae71900-ef6a-11e9-9c71-020ab208aeec.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/cis-hook-and-R-bee.ts

**Comment by nazmariam** [comment]
hi! could you assign this issue to me?
