### ISSUE TITLE
feat: Cis-hook with tail

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#181]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/66810396-29e5ab00-ef6a-11e9-9fd2-b2f7b17b045c.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/cis-hook-with-tail.ts

**Comment by madmaxWMFU** [comment]
Hi @TroyTae , I would love to help to create this template. Can I?
