### ISSUE TITLE
feat: Cis-loaf with tail

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#182]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/66811081-71206b80-ef6b-11e9-97ac-06c6b0405c1c.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/cis-loaf-with-tail.ts

**Comment by Croftyland** [comment]
@TroyTae can I take this issue?
