### ISSUE TITLE
feat: Cis-long barge with tail

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#183]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/66811199-a2993700-ef6b-11e9-9a7a-580dbbe6c518.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/cis-long-barge-with-tail.ts

**Comment by Croftyland** [comment]
@TroyTae can I take this issue?
