### ISSUE TITLE
feat: Cis-long boat with tail

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#184]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/66811312-d5dbc600-ef6b-11e9-921a-101d1f631757.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/cis-long-boat-with-tail.ts

**Comment by Croftyland** [comment]
@TroyTae can I take this issue?
