### ISSUE TITLE
feat: Cis-mirrored R-bee

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#186]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/66811515-32d77c00-ef6c-11e9-90e8-c4f61a94073b.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/cis-mirrored-R-bee.ts

**Comment by Croftyland** [comment]
Can I take it?
