### ISSUE TITLE
feat: Double claw

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#223]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67097360-e94d9200-f1f4-11e9-8bc9-99e68f2654c1.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/double-claw.ts

**Comment by sneha122** [comment]
I would like to help in this issue..
Could you assign it to me?
