### ISSUE TITLE
feat: Fourteener

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#225]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67097830-e99a5d00-f1f5-11e9-8322-47670eb4f303.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/fourteener.ts

**Comment by LeoVie** [comment]
Hi, I'd like to do this. :)

**Comment by LeoVie** [comment]
If there's nothing to complain in my pull request, I'll do some more issues. :)
