### ISSUE TITLE
feat: Fuse with tail and integral

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#226]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67097881-0898ef00-f1f6-11e9-83e8-a539bd2c0e67.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/fuse-with-tail-and-integral.ts

**Comment by LeoVie** [comment]
I'll do this. :)
