### ISSUE TITLE
feat: Fuse with tail and long tail

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#227]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67098017-531a6b80-f1f6-11e9-9ba9-f2d7c4a36b10.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/fuse-with-tail-and-long-tail.ts

**Comment by LeoVie** [comment]
I'm taking this. :)
