### ISSUE TITLE
feat: Fuse with tail and very long tail

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#228]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67098080-73e2c100-f1f6-11e9-991c-40e55a4b3f6a.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/fuse-with-tail-and-very-long-tail.ts

**Comment by GeovRodri** [comment]
I can take this one
