### ISSUE TITLE
feat: Fuse with two long tails

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#229]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67098282-db990c00-f1f6-11e9-9964-ed733d5cb6ec.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/fuse-with-two-long-tails.ts

**Comment by sneha122** [comment]
Hey I would like to take this issue..
Could you assign it to me?
