### ISSUE TITLE
feat: Eater bridge eater

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#234]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67099784-83afd480-f1f9-11e9-8b69-276fbccda0b3.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/eater-bridge-eater.ts

**Comment by mayconsacht** [comment]
Hello! I can take this one.
