### ISSUE TITLE
feat: Eater head siamese long snake

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#237]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67100074-ffaa1c80-f1f9-11e9-8280-137d7f4a4ed2.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/eater-head-siamese-long-snake.ts

**Comment by waahhhh** [comment]
On it!
