### ISSUE TITLE
feat: Eater head siamese snake

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#238]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67100144-210b0880-f1fa-11e9-8ddb-af4d649142d5.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/eater-head-siamese-snake.ts

**Comment by Mazurr** [comment]
I work on this issue
