### ISSUE TITLE
feat: Eater tail siamese eater tail

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#239]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67100280-544d9780-f1fa-11e9-88b8-fa5aebf1d531.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/eater-tail-siamese-eater-tail.ts

**Comment by whitemalt** [comment]
#265 let check this PR.
