### ISSUE TITLE
feat: Eater tail siamese long snake

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#240]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67100333-6c251b80-f1fa-11e9-88fc-de6f6848b6f6.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/eater-tail-siamese-long-snake.ts

**Comment by EXLER** [comment]
I am working on this issue :)
