### ISSUE TITLE
feat: Eater tail siamese snake

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#241]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67100385-85c66300-f1fa-11e9-945d-5225bdf64d58.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/eater-tail-siamese-snake.ts

**Comment by vkhalaim** [comment]
https://github.com/TroyTae/game-of-life/pull/264
