### ISSUE TITLE
feat: Eater with tail feather

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#244]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67100483-b73f2e80-f1fa-11e9-82ec-08db4c4c60d6.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/eater-with-tail-feather.ts

**Comment by vkhalaim** [comment]
Hi! I'll take care of it
