### ISSUE TITLE
feat: Egyptian walk

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#245]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67100549-d473fd00-f1fa-11e9-9b49-7e8fde47f14d.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/egyptian-walk.ts

**Comment by JorgeAndd** [comment]
I will work on this one :)
