### ISSUE TITLE
feat: Gull with tub

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#249]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67100779-48160a00-f1fb-11e9-800d-484c97df22fc.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/gull-with-tub.ts

**Comment by LeoVie** [comment]
I'd like to do this.

**Comment by TroyTae** [comment]
closed by #254
