### ISSUE TITLE
feat: Aircraft carrier

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#26]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/66534824-738d5a80-eb52-11e9-81a6-5129a9f1cbad.png)

Please work at this line: https://github.com/TroyTae/game-of-life/blob/master/src/index.ts#L43-L45

**Comment by papuruth** [comment]
May I?

**Comment by TroyTae** [comment]
@papuruth 
Sure! Opensource always open :)
