### ISSUE TITLE
feat: Aries betwixt two blocks

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#28]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/66534959-eb5b8500-eb52-11e9-9021-c1bdc7602f19.png)

Please work at this line: https://github.com/TroyTae/game-of-life/blob/master/src/index.ts#L55-L57

**Comment by AugustasV** [comment]
I would like to take make this pattern!

**Comment by TroyTae** [comment]
@AugustasV 
Cool! Thank you for your interest :)

**Comment by TroyTae** [comment]
closed by #32
