### ISSUE TITLE
feat: Hat siamese vase

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#280]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67162267-569c2700-f39d-11e9-846e-fe633b62e307.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/hat-siamese-vase.ts

**Comment by vkhalaim** [comment]
Hi! I'll take care of this as well :)
