### ISSUE TITLE
feat: Hexagonal key

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#281]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67162289-77647c80-f39d-11e9-9581-575485e2ad4a.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/hexagonal-key.ts

**Comment by vkhalaim** [comment]
Hi! I'll take care of it
