### ISSUE TITLE
feat: Asymmetric amphisbaena

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#29]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/66534987-075f2680-eb53-11e9-8bdc-a2b2dd791f52.png)

Please work at this line: https://github.com/TroyTae/game-of-life/blob/master/src/index.ts#L52-L54

**Comment by hiteda** [comment]
Could I take this?

**Comment by TroyTae** [comment]
@hiteda 
Sure!
Feel free to send a PR :)

**Comment by hiteda** [comment]
Thanks for the opportunity! Pretty neat little web app you've got here. I've always been a fan of Conway's game of life.

**Comment by TroyTae** [comment]
Me too, I love game of life :)
Thank you for your contribution again!

**Comment by TroyTae** [comment]
closed by #30
