### ISSUE TITLE
feat: Hook-with-tail tail siamese snake

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#295]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67176815-98ad8300-f406-11e9-97a4-4ee2b4fe606b.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/hook-with-tail-tail-siamese-snake.ts

**Comment by charlygg** [comment]
Hi, Could I work in this issue?

**Comment by TroyTae** [comment]
@charlygg Sure!

**Comment by TroyTae** [comment]
closed by #298
