### ISSUE TITLE
feat: Hungry hat

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#297]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67176859-d0b4c600-f406-11e9-8c17-27a39250759a.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/hungry-hat.ts

**Comment by vkhalaim** [comment]
Hi! I'll tale care of this
