### ISSUE TITLE
feat: Inflected long snake

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#303]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67218855-0d61db00-f462-11e9-83ed-933aa6aee334.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/inflected-long-snake.ts

**Comment by ryuakaa** [comment]
I'll do it 😄
