### ISSUE TITLE
feat: Integral with tub and tail

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#313]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67221428-63388200-f466-11e9-8fa4-9a69d3b4e002.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/integral-with-tub-and-tail.ts

**Comment by vkhalaim** [comment]
Please, assign me)
