### ISSUE TITLE
feat: Inverted double claw

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#316]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67221626-bdd1de00-f466-11e9-8c51-168efc00c6ec.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/inverted-double-claw.ts

**Comment by S10MC2015** [comment]
are the 0s white and 1s black?
also, I am claiming the issue.

**Comment by TroyTae** [comment]
@S10MC2015 
Yup, 0 is white(dead) and 1 is black(live)!
