### ISSUE TITLE
feat: Mango

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#330]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67355625-aee84a00-f592-11e9-8202-fed9690c1a8c.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/mango.ts

**Comment by gunasekara** [comment]
I'm working on this

**Comment by gunasekara** [comment]
this is the fixed PR for this https://github.com/TroyTae/game-of-life/pull/338
