### ISSUE TITLE
feat: Mango with block on dock

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#331]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67355695-da6b3480-f592-11e9-9b31-5d4d35ae5134.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/mango-with-block-on-dock.ts

**Comment by lasantha57** [comment]
I will work on this
