### ISSUE TITLE
feat: Mickey Mouse

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#332]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67355727-f53da900-f592-11e9-8285-baf8c8088a23.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/mickey-mouse.ts

**Comment by fedebabrauskas** [comment]
Can I be assigned to this issue?

Thanks!
