### ISSUE TITLE
feat: Moose antlers

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#334]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67355821-49e12400-f593-11e9-836f-185ff64ef275.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/moose-antlers.ts

**Comment by fedebabrauskas** [comment]
Can I be assigned for this issue?
