### ISSUE TITLE
feat: O quad-loaf

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#340]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67369268-ace2b300-f5b3-11e9-8ce9-7df6bc8c1ef9.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/o-quad-loaf.ts

**Comment by adamxtokyo** [comment]
On it :)

**Comment by adamxtokyo** [comment]
Thanks! 😁
Happy I could contribute 🎉
