### ISSUE TITLE
feat: Omnibus with tubs

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#342]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67369429-f3381200-f5b3-11e9-8cc3-7a319cb95555.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/omnibus-with-tubs.ts

**Comment by lasantha57** [comment]
I will work on this
