### ISSUE TITLE
feat: Ortho-loaf on table

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#343]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67369480-0ba82c80-f5b4-11e9-8c8c-6ebfdf4664cf.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/ortho-loaf-on-table.ts

**Comment by lasantha57** [comment]
I'm working on this
