### ISSUE TITLE
feat: Pond on pond

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#350]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67376076-7e1e0a00-f5be-11e9-9519-a24b82f55d05.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/pond-on-pond.ts

**Comment by gunasekara** [comment]
i will fix this

**Comment by gunasekara** [comment]
this is the PR for the issue https://github.com/TroyTae/game-of-life/pull/406
