### ISSUE TITLE
feat: Professor

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#351]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67376138-98f07e80-f5be-11e9-9087-ea18508aaf9f.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/professor.ts

**Comment by gunasekara** [comment]
i will fix this

**Comment by gunasekara** [comment]
this is the PR for the fix  https://github.com/TroyTae/game-of-life/pull/407
