### ISSUE TITLE
feat: Python siamese snake

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#352]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67376205-b1f92f80-f5be-11e9-8c83-5785d1e01d19.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/python-siamese-snake.ts

**Comment by gunasekara** [comment]
i will fix this

**Comment by gunasekara** [comment]
here is the PR for issue https://github.com/TroyTae/game-of-life/pull/408
