### ISSUE TITLE
feat: Loaf back tie loaf

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#359]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67406542-2b117a80-f5f1-11e9-801e-41ef4d6c27a6.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/loaf-back-tie-loaf.ts

**Comment by sp4ceunicorn** [comment]
Hi, can I take this other one?
