### ISSUE TITLE
feat: Barge with long tail

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#36]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/66548998-5326c580-eb7d-11e9-90e1-42f5cfc7ef30.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/barge-with-long-tail.ts

**Comment by elkhorn360** [comment]
I'll do this as well
