### ISSUE TITLE
feat: Loaf siamese loaf

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#360]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67406873-a115e180-f5f1-11e9-880c-dbcabad5b8eb.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/loaf-siamese-loaf.ts

**Comment by InquiridorTechie** [comment]
I am working on it.
