### ISSUE TITLE
feat: Loaf tie eater-with-tail

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#361]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67407121-023db500-f5f2-11e9-9683-eb60c6c85d1d.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/loaf-tie-eater-with-tail.ts

**Comment by psy0ch** [comment]
ill check this out
