### ISSUE TITLE
feat: Long boat tie ship

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#364]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67407515-927bfa00-f5f2-11e9-8cdb-a5e8639893c2.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/long-boat-tie-ship.ts

**Comment by lasantha57** [comment]
I'm on this
