### ISSUE TITLE
feat: Long cis-hook with tail

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#367]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67408029-55643780-f5f3-11e9-83bf-c5c3eea97c4a.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/long-cis-hook-with-tail.ts

**Comment by InquiridorTechie** [comment]
working on it.
