### ISSUE TITLE
feat: Long cis-shillelagh

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#368]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67408273-b5f37480-f5f3-11e9-8fe5-855013ab14df.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/long-cis-shillelagh.ts

**Comment by InquiridorTechie** [comment]
working on it.
