### ISSUE TITLE
feat: Long claw with tail

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#369]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67408433-ecc98a80-f5f3-11e9-84d4-c1072fbf3eb6.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/long-claw-with-tail.ts

**Comment by PHIQW** [comment]
I'd like to work on this request
