### ISSUE TITLE
feat: Barge with very long tail

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#37]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/66549196-bd3f6a80-eb7d-11e9-9e39-5c64168812ef.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/barge-with-very-long-tail.ts

**Comment by elkhorn360** [comment]
I'll do this as well :)
