### ISSUE TITLE
feat: Long hook with tail

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#370]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67408567-28fceb00-f5f4-11e9-8822-579ba7df29c3.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/long-hook-with-tail.ts

**Comment by criscros-garcia** [comment]
working on this¡
