### ISSUE TITLE
feat: Long integral with boat

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#373]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67408842-9f015200-f5f4-11e9-98b7-85ab5b71f5c6.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/long-integral-with-boat.ts

**Comment by criscros-garcia** [comment]
Working on this¡
