### ISSUE TITLE
feat: Long shillelagh

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#376]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67409255-47171b00-f5f5-11e9-8f27-231bd71d12ae.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/long-shillelagh.ts

**Comment by cedarfall** [comment]
@TroyTae I'm taking this issue.
