### ISSUE TITLE
feat: Long snake siamese long snake

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#379]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67409604-c0167280-f5f5-11e9-87fd-30d873eb0471.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/long-snake-siamese-long-snake.ts

**Comment by radhais** [comment]
Please assign this to me, I am working on it
