### ISSUE TITLE
feat: Long tub-claw tail

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#380]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67409726-eb995d00-f5f5-11e9-9eae-5ee557872261.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/long-tub-claw-with-tail.ts

**Comment by radhais** [comment]
Working on this one, will send PR soon
