### ISSUE TITLE
feat: Long3 canoe

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#415]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67507219-7434fd80-f6c9-11e9-93b6-59413bdbd2cb.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/long3-canoe.ts

**Comment by dinukad** [comment]
@TroyTae  I'm working on this. Please assign this to me.

**Comment by dinukad** [comment]
@TroyTae Please refer PR: https://github.com/TroyTae/game-of-life/pull/448
