### ISSUE TITLE
feat: Long3 hook with tail

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#416]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67507378-b9592f80-f6c9-11e9-8161-0dc448502835.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/long3-hook-with-tail.ts

**Comment by dinukad** [comment]
@TroyTae  I'm working on this. Please assign this to me.

**Comment by dinukad** [comment]
@TroyTae Please refer PR: https://github.com/TroyTae/game-of-life/pull/446
