### ISSUE TITLE
feat: Long3 integral

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#417]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67507446-ddb50c00-f6c9-11e9-8335-8a60e6364587.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/long3-integral.ts

**Comment by dinukad** [comment]
@TroyTae  I'm working on this. Please assign this to me.

**Comment by dinukad** [comment]
@TroyTae Please refer PR: https://github.com/TroyTae/game-of-life/pull/445
