### ISSUE TITLE
feat: Long3 shillelagh

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#418]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67507553-1228c800-f6ca-11e9-98c7-ccf79abb2246.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/long3-shillelagh.ts

**Comment by dinukad** [comment]
@TroyTae  I'm working on this. Please assign this to me.

**Comment by dinukad** [comment]
@TroyTae Please refer PR: https://github.com/TroyTae/game-of-life/pull/431
