### ISSUE TITLE
feat: Long4 canoe

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#424]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67508615-50bf8200-f6cc-11e9-907b-988ebca70af8.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/long4-canoe.ts

**Comment by lakmal777git** [comment]
I will take this issue

**Comment by lakmal777git** [comment]
Please refer PR
https://github.com/TroyTae/game-of-life/pull/450
