### ISSUE TITLE
feat: Long4 hook with tail

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#425]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67508748-911f0000-f6cc-11e9-8920-06f027309177.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/long4-hook-with-tail.ts

**Comment by lakmal777git** [comment]
I will take this issue

**Comment by lakmal777git** [comment]
Please refer the pull request 
https://github.com/TroyTae/game-of-life/pull/467
