### ISSUE TITLE
feat: Long4 shillelagh

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#426]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67508862-ca577000-f6cc-11e9-8028-be91b80a59ab.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/long4-shillelagh.ts

**Comment by lakmal777git** [comment]
I will take this issue

**Comment by lakmal777git** [comment]
Please refer the PR 
https://github.com/TroyTae/game-of-life/pull/453
