### ISSUE TITLE
feat: Beehive at beehive

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#44]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/66614215-1bfaf780-ec03-11e9-876d-1bf2be03d02e.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/beehive-at-beehive.ts

**Comment by hasalassh** [comment]
@TroyTae Let me work on this...!

**Comment by hasalassh** [comment]
@TroyTae I have created pull request https://github.com/TroyTae/game-of-life/pull/55 for above task. Please review and merge...!
