### ISSUE TITLE
feat: Beehive at claw

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#45]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/66614265-4d73c300-ec03-11e9-9ed4-358cc0ff161e.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/beehive-at-claw.ts

**Comment by hasalassh** [comment]
@TroyTae Let me work on this...!

**Comment by hasalassh** [comment]
@TroyTae I have created a PR https://github.com/TroyTae/game-of-life/pull/58 for above task...!
