### ISSUE TITLE
feat: Beehive at loaf

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#46]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/66614307-78f6ad80-ec03-11e9-98d4-3c005e041e21.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/beehive-at-loaf.ts

**Comment by chaturanganamal** [comment]
I'll take this one

**Comment by chaturanganamal** [comment]
Created a PR
