### ISSUE TITLE
feat: Beehive on cap

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#47]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/66614328-9c215d00-ec03-11e9-98bc-a0f3aba51e02.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/beehive-on-cap.ts

**Comment by droidttk** [comment]
I'll take this one

**Comment by droidttk** [comment]
Created a PR. Please review and merge #61
