### ISSUE TITLE
feat: Beehive on dock

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#48]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/66614378-c6731a80-ec03-11e9-8c00-506483f5a6bb.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/beehive-on-dock.ts

**Comment by droidttk** [comment]
I'll take this one

**Comment by droidttk** [comment]
Created a PR. Please review and merge #60
