### ISSUE TITLE
feat: Quad pseudo still life

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#481]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67636863-282bc800-f918-11e9-8921-093e767d6656.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/quad-pseudo-still-life.ts

**Comment by ronaldsin** [comment]
I would like to work on this one
