### ISSUE TITLE
feat: R-bee and snake

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#483]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67639090-f3773b00-f92e-11e9-807d-f21c24472e1a.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/r-bee-and-snake.ts

**Comment by dickyw71** [comment]
I will take a look at this one.

**Comment by dickyw71** [comment]
Pull request raised please merge.
