### ISSUE TITLE
feat: R-bee on beehive

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#484]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67639106-1144a000-f92f-11e9-81a0-575395a2f9b3.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/r-bee-on-beehive.ts

**Comment by jarofblueberries** [comment]
Ok, I do more :)
