### ISSUE TITLE
feat: R-bee with feather

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#485]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67639122-320cf580-f92f-11e9-97cb-54d3f4850966.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/r-bee-with-feather.ts

**Comment by DanielSauve** [comment]
I have a PR up to add this in :)
