### ISSUE TITLE
feat: Beehive on table

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#49]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/66614413-f0c4d800-ec03-11e9-963f-ed1462e5a134.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/beehive-on-table.ts

**Comment by droidttk** [comment]
I'll take this one

**Comment by droidttk** [comment]
Created PR. Please review and merge #59
