### ISSUE TITLE
feat: Triple pseudo still life

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#495]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67654485-14707800-f991-11e9-8197-391bf82fa018.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/pseudo-still-life/triple-pseudo-still-life.ts

**Comment by jarofblueberries** [comment]
I take this :)
