### ISSUE TITLE
feat: Sesquihat

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#497]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67654592-631e1200-f991-11e9-8aa7-e7c5a510d34c.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/sesquihat.ts

**Comment by adamxtokyo** [comment]
I'm claiming this one 😛
