### ISSUE TITLE
feat: Toad pattern

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#5]
Let's make Toad pattern!

Here is the gif:
![d8591bf0b1bb8ca7a646ca2b9ecb73c5b63f6e66b90fbbf72e359a3661f4c49483c45b67e93569fb5df2247597a14551bbd7fea03e47e2a45138992750e2e72f61bf6f0dcce476ecdeec4eb4197e9894cef7e794062914ba6ac7eb841ea7b046](https://user-images.githubusercontent.com/20078201/66025585-cbfca080-e531-11e9-9d49-bcea55ff365c.gif)

And here is the example of blinker pattern:
https://github.com/TroyTae/game-of-life/blob/master/src/index.ts#L13-L19

![7e9082a14802562056e2f62e959cd0e1dba8a9f2f75622b59a65eb31a870840399c8eaa95f7c86f3e3c32d29f3c750177c7764f79f9eb135251be3bccc59c1f93304de712b2c16d40ea1f42121f96fbbc2b7dc84d5063cc2de77a438d176fbfd](https://user-images.githubusercontent.com/20078201/66025644-ef275000-e531-11e9-90c9-3e2dfcba0136.gif)

**Comment by maciekgrzybek** [comment]
Hey I've added PR for that one - https://github.com/TroyTae/game-of-life/pull/7

**Comment by TroyTae** [comment]
closed by #7
