### ISSUE TITLE
feat: Beehive with bend tail

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#50]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/66614499-41d4cc00-ec04-11e9-92f1-b8387d74076c.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/beehive-with-bend-tail.ts

**Comment by chaturanganamal** [comment]
I'll take this one

**Comment by chaturanganamal** [comment]
Created a PR
