### ISSUE TITLE
feat: Ship tie snake

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#501]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67654755-f22b2a00-f991-11e9-82d4-a78658d64ca0.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/ship-tie-snake.ts

**Comment by Reisclef** [comment]
I'll do this one. :)
