### ISSUE TITLE
feat: Sidewalk

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#519]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67735830-b737fd80-fa48-11e9-91c8-9e3953a7529e.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/sidewalk.ts

**Comment by pabus** [comment]
Hi, @TroyTae, I'm interested on this. Please assign this to me.
