### ISSUE TITLE
feat: Beehive with tail

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#52]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/66614586-96784700-ec04-11e9-96fb-2b833d3e46d9.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/beehive-with-tail.ts

**Comment by donaldducky** [comment]
Hi @TroyTae this is a fun little project! 😍
