### ISSUE TITLE
feat: Skew R-bees

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#520]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67735864-d171db80-fa48-11e9-9b67-cf63b9a4e3b6.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/skew-r-bees.ts

**Comment by pabus** [comment]
Hi, @TroyTae, I'm interested on this. Please assign this to me.

**Comment by pabus** [comment]
Hi @TroyTae, bump
