### ISSUE TITLE
feat: Small lake

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#521]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67735925-f9f9d580-fa48-11e9-825f-56ce937f7447.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/small-lake.ts

**Comment by pabus** [comment]
Hi, @TroyTae, I'm interested on this. Please assign this to me.
