### ISSUE TITLE
feat: Snake

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#522]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67735975-1f86df00-fa49-11e9-8831-87442c71749f.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/snake.ts

**Comment by pabus** [comment]
Hi, @TroyTae, I'm interested on this. Please assign this to me.
