### ISSUE TITLE
feat: Snake bridge snake

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#523]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67736020-49400600-fa49-11e9-818e-fef756134c8c.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/snake-bridge-snake.ts

**Comment by hippohipporhino** [comment]
I will try my hand at this one 👍. Starting on it now!
