### ISSUE TITLE
feat: Snake siamese snake

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#524]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67736043-61b02080-fa49-11e9-84c4-708eeb7ce62a.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/snake-siamese-snake.ts

**Comment by YaMo97** [comment]
Hi @TroyTae, I'd like to take this up. Please assign it to me.
