### ISSUE TITLE
feat: Snake with feather

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#526]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67736080-9de38100-fa49-11e9-89b3-fdf097f29e6b.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/snake-with-feather.ts

**Comment by Udayasri1988** [comment]
Assigned this to me
