### ISSUE TITLE
feat: Snorkel loop

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#527]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67739419-c2455a80-fa55-11e9-8a3d-24a11c470773.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/snorkel-loop.ts

**Comment by Udayasri1988** [comment]
Assigned this to me
