### ISSUE TITLE
feat: Super mango

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#530]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67739670-970f3b00-fa56-11e9-93f5-feee60216d48.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/super-mango.ts

**Comment by knappologi** [comment]
Will contribute with a pull request within a few hours with a super mango :)
