### ISSUE TITLE
feat: Symmetric scorpion

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#532]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67739754-db024000-fa56-11e9-9f55-f0e288e48a1d.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/symmetric-scorpion.ts

**Comment by Udayasri1988** [comment]
Please assign this to me
