### ISSUE TITLE
feat: Symmetrical synapse

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#533]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67739792-fcfbc280-fa56-11e9-945b-0a7f5576cf7f.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/symmetrical-synapse.ts

**Comment by suleiManiac** [comment]
Hello, I'm sorry to disturb and I'm probably going to sound stupid before this is done. I apologize in advance. So, basically what is needed is to create this pattern using arrays as it is in the symmetrical-synapse file, yes? Can I just create the array and hardcode the 1's and 0's to get the pattern?
In case you couldn't tell, I'm a first timer and code newbie. Thanks

**Comment by TroyTae** [comment]
@suleiManiac 
You don't need to apologize :)
Yes if you wanna make this pattern, open `symmetrical-synapse.ts` file and make arrays!
As you said black is 1 and white is 0.
After your working that file will make a pattern with my engine!

**Comment by suleiManiac** [comment]
@TroyTae 
Thank you. I have created the pattern in the file as per your instructions and created a pull request. Not sure what's next.
