### ISSUE TITLE
feat: Very long claw with tail

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#560]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67860654-c2cb1780-fb61-11e9-826d-b6448ce08c39.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/strict-still-life/very-long-claw-with-tail.ts

**Comment by alexandrehcdc** [comment]
I'd like to work on this issue if it's ok to you :)
