### ISSUE TITLE
feat: Very long prodigal

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#564]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67861197-fb1f2580-fb62-11e9-92f9-f18183ca0090.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/strict-still-life/very-long-prodigal.ts

**Comment by srbaxter** [comment]
I'll do this one
