### ISSUE TITLE
feat: Teardrop with cape

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#585]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67926214-c8c00780-fbf8-11e9-9f60-1458fdbcf7bc.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/strict-still-life/teardrop-with-cape.ts

**Comment by IamShivamJaiswal** [comment]
hi I will do this
