### ISSUE TITLE
feat: Teardrop with claw

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#587]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67926662-e93c9180-fbf9-11e9-9e74-37788cca225c.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/strict-still-life/teardrop-with-claw.ts

**Comment by AndrewCleve** [comment]
I can take this one
