### ISSUE TITLE
feat: Twin hat

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#592]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67926907-9ca58600-fbfa-11e9-9d61-8b8dbf95f337.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/strict-still-life/twin-hat.ts

**Comment by AndrewCleve** [comment]
I've got this one
