### ISSUE TITLE
feat: Lighthouse pattern

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#6]
Let's make Lighthouse pattern!

Here is the gif:
![7431b91bc84d807b456db58ce52d4afcd8b927a5629d1df5aac3ae279283950e9922017008a4953b6e02891dacc1b3df8ecc786ff11bb9a374cdce189c95b50e4854fe526ff20dc16575e674b87b460dc68a3997974b6686cc0ddc6f076a020f](https://user-images.githubusercontent.com/20078201/66025747-2b5ab080-e532-11e9-993d-48b1842996f7.gif)

And here is the example of blinker pattern:
https://github.com/TroyTae/game-of-life/blob/master/src/index.ts#L13-L19

![7e9082a14802562056e2f62e959cd0e1dba8a9f2f75622b59a65eb31a870840399c8eaa95f7c86f3e3c32d29f3c750177c7764f79f9eb135251be3bccc59c1f93304de712b2c16d40ea1f42121f96fbbc2b7dc84d5063cc2de77a438d176fbfd](https://user-images.githubusercontent.com/20078201/66025738-25fd6600-e532-11e9-8cb3-57ce15be55cf.gif)

**Comment by maciekgrzybek** [comment]
For this one as well :) - https://github.com/TroyTae/game-of-life/pull/8

**Comment by maciekgrzybek** [comment]
By the way, I've never heard about the game of life before, but you really got me interested :) are you free to chat about it on slack/WhatsApp or something similar?

**Comment by TroyTae** [comment]
Thank you for your contribution!
Unfortunately I'm not expert about game of life.
I also study about this and then I create this repo.
Maybe you can get detail information what you want in other community.

**Comment by TroyTae** [comment]
closed by #8
