### ISSUE TITLE
feat: Tub

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#600]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/67939887-d1730680-fc15-11e9-93ff-4d739d99ed0d.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/strict-still-life/tub.ts

**Comment by akdir** [comment]
I will make this @TroyTae, if you like me to do it.
