### ISSUE TITLE
feat: Bi-boat

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#63]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/66631162-9dbd4600-ec40-11e9-9446-1f4477a2c4b7.png)

Please work at this line: https://github.com/TroyTae/game-of-life/blob/master/src/life/pseudo-still-life/bi-boat.ts

**Comment by kalpananegi** [comment]
I'll do
