### ISSUE TITLE
feat: Bi-pond

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#66]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/66631336-ea088600-ec40-11e9-9f63-3f97b4913215.png)

Please work at this line: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/bi-pond.ts

**Comment by kalpananegi** [comment]
I will take this

**Comment by kalpananegi** [comment]
Done #67

**Comment by TroyTae** [comment]
closed by #67
