### ISSUE TITLE
feat: Almosymmetric

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#674]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/74295722-3dbce480-4d85-11ea-9900-b5c8980250ed.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/almosymmetric.ts

**Comment by CAMYR71** [comment]
I'll pick this one up.  Working on it!
