### ISSUE TITLE
achims-p114 missing

### ISSUE THREAD

**Issue by CAMYR71** [TroyTae/game-of-life#679]
Receiving following error when running `npm run start` .   Program still runs

> ERROR in ./src/index.ts
Module not found: Error: Can't resolve './life/oscillator/achims-p114' in '/xxx/xxx/GitHub/game-of-life/src'
 @ ./src/index.ts 692:20-60

**Comment by TroyTae** [comment]
Oh sorry for missing it.
This changes are committed in release branch (https://github.com/TroyTae/game-of-life/tree/release)
Now I merge this branch. Thank you :)
