### ISSUE TITLE
feat: $rats

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#694]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/75607429-6a6d4c00-5b3a-11ea-8b49-fc59139b3a79.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/billiard-table/%24rats.ts

If you wanna tackle this issue, please leave comment.  
I'll assign to you!  

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by mand0ng** [comment]
good day i want on this project. i already completed this on my local. can you tell and guide me whats my next step thank you.

**Comment by TroyTae** [comment]
@mand0ng 
Hey!
Thank you for your work.
Did you see this guide?
(https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md)
You need to fork this repository and make a PR :)

**Comment by mand0ng** [comment]
@TroyTae sorry i really dont know how the flow when contributing to an open source project. hope u understand.
Anyhow i have forked the repo and created a new branch and made a PR.  also i have run npm run test:lint and i think results are fine.  hoping my actions are helpful. 
i am looking forward on working on another issue, also i am open in improving my submitted changes if needed.

**Comment by TroyTae** [comment]
@mand0ng 
Please do not apologize.
You did this work perfectly!
Now I start to review your code :)
