### ISSUE TITLE
feat: 1-2-3-4

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#697]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/75622187-12d5eb80-5be1-11ea-87bf-55bf8fa8c39b.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/billiard-table/1-2-3-4.ts

If you wanna tackle this issue, please leave comment.  
I'll assign to you!  

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by Dev-Akash** [comment]
Hi there, I am interested in doing contribution in this.

**Comment by Dev-Akash** [comment]
Hi there,
I have create a pull request, please review it !

**Comment by TroyTae** [comment]
closed by @Dev-Akash in #708 🎉🎉
