### ISSUE TITLE
feat: 1 beacon

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#698]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/75622224-78c27300-5be1-11ea-9334-a23a16529866.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/1-beacon.ts

If you wanna tackle this issue, please leave comment.  
I'll assign to you!  

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by Dev-Akash** [comment]
Hi there, 
I have update the beacon.ts file as required, Please review the PR
