### ISSUE TITLE
feat: 101

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#699]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/75622272-e1115480-5be1-11ea-9470-305eea5aefe1.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/101.ts

If you wanna tackle this issue, please leave comment.  
I'll assign to you!  

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by zolbooo** [comment]
Hi. Added this pattern, please review my code :)
