### ISSUE TITLE
feat: Pick color for each pattern

### ISSUE THREAD

**Issue by LoukasPap** [TroyTae/game-of-life#723]
Hello! I see that there are only 3 used colors to every pattern (black for survive, white for dead, and grey for the background). I think that it would be a nice addition to let each contributor put his own colors to the pattern he creates, so that it be more beautiful!
So, if you approve it, can I start improving the program?😄

**Comment by TroyTae** [comment]
@LoukasPap 
Sure it's fantastic!
related with https://github.com/TroyTae/game-of-life/issues/714#issuecomment-599777805

**Comment by TroyTae** [comment]
Information for you :)
Color constants: https://github.com/TroyTae/game-of-life/blob/master/src/constants.ts
Engine: https://github.com/TroyTae/game-of-life/blob/master/src/engine.ts
