### ISSUE TITLE
Improve site 

### ISSUE THREAD

**Issue by DinosXa** [TroyTae/game-of-life#725]
I was thinking of maybe improving the html in the site. Maybe adding some cool scc features to make the squares coverable. just in general adding a bit of life. 

what are your thoughts?

**Comment by TroyTae** [comment]
I already have improving website plan (make playgound, split each pattern page, etc...)
But that's another story.
I interested in your idea :)
Can you explain about scc?
I don't know about it.

**Comment by LoukasPap** [comment]
Maybe he means css? (Cascading Style Sheets)
I would like to help with the improvisation of the html.

**Comment by DinosXa** [comment]
sorry iwas typing on my phone and auto correct made css to scc .

**Comment by TroyTae** [comment]
After making plan, I'll create some issues that labeled `enhancement`.
If you want to solve them, please leave comment!
