### ISSUE TITLE
build: split pages

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#742]
Now there is only one page for drawing many of patterns.
We need to split each patterns.

Requires:
1. Each patterns need to have their own page
2. We won't make SPA but title and meta data should be changed according to page
3. Duplicated code should be reused as split js

**Comment by LoukasPap** [comment]
Me and @DinosXa could do it! :)

**Comment by LoukasPap** [comment]
I just have a question. What is SPA?

**Comment by TroyTae** [comment]
@LoukasPap 
I already start this work.
But Design work is being delayed.
I can write css but not good at design 😅 
Can you help me about this?

**Comment by LoukasPap** [comment]
Sure, so what shall we do about the design?

**Comment by TroyTae** [comment]
Can you show me design draft in any form?
(image, zeppelin or photoshop etc...)

**Comment by LoukasPap** [comment]
Do you want the design of the page as a photo?

**Comment by TroyTae** [comment]
Format is not important!
But I wanna see draft before appying :)

**Comment by LoukasPap** [comment]
I do not know what design draft is 😢 Maybe a good url that explains it.

**Comment by TroyTae** [comment]
I mean really design: https://www.myelephants.org/web-design/ideas-to-make-good-web-design/
We need to think about Layout/Component/Theme etc...

**Comment by zolbooo** [comment]
Hi 👋 
There is sample design created by @kusenis:

![611A41DF-C2CE-47A9-ABA7-C56117370CE0](https://user-images.githubusercontent.com/33338165/77745431-395b3b00-7056-11ea-8188-770284f99216.png)

As for me, it looks good for mobile devices, but it could be great place to start 😁

**Comment by DinosXa** [comment]
this looks nice :)

**Comment by TroyTae** [comment]
@zolbooo 
Thank you for your suggestion!
How can I find that page?
Now I look around repositories of @kusenis but I cannot find that.

**Comment by LoukasPap** [comment]
I am going to post my suggestion at night :)

**Comment by zolbooo** [comment]
@TroyTae
Here is his figma project: https://www.figma.com/file/LqVuDb4yqKKpAqExeZ0l2q/Game-of-life---redesign?node-id=1%3A2

**Comment by TroyTae** [comment]
@zolbooo 
cool! Thank you :)

**Comment by LoukasPap** [comment]
Here is my suggestion :)
https://www.figma.com/file/YR3SziYxNQcIlZgwt9vAfq/GOL?node-id=0%3A1
On **patterns** you will be able to choose which type of patterns you want to see.
On **search** you will search a pattern with specific name
On **filter** you will filter they way that patterns are showing up (for example: one at a time, all together, etc.)
You can also change the color of the main theme AND the side them. Plus, the color of the pattern.
On **About** section the guest can see information about Game of Life (it is a cellular automaton, it was made by John Horton, blah blah...) 😄

**Comment by DinosXa** [comment]
this will need html and css additions. what are you're thoughts @TroyTae  ?

**Comment by TroyTae** [comment]
@LoukasPap @DinosXa 
Sorry to late response.
This issue is for discussing split pages configuration and that is complete.
I'll make a new issue for discussing design!
