### ISSUE TITLE
feat: reforming web design

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#750]
Suggestion:
1. https://www.figma.com/file/LqVuDb4yqKKpAqExeZ0l2q/Game-of-life---redesign?node-id=1%3A2 by @zolbooo 
2. https://www.figma.com/file/YR3SziYxNQcIlZgwt9vAfq/GOL?node-id=0%3A1 by @LoukasPap

Current Pages:
 - List page
![image](https://user-images.githubusercontent.com/20078201/78144307-677fb700-746a-11ea-9ba3-176cd5391e2c.png)
 - Each pattern pages
![image](https://user-images.githubusercontent.com/20078201/78144383-7d8d7780-746a-11ea-84df-30594f964bd2.png)

**Comment by TroyTae** [comment]
@LoukasPap @DinosXa 
Please discussing about web design in here :)

**Comment by LoukasPap** [comment]
So we want the general design that it will be applied to every single pattern?

**Comment by TroyTae** [comment]
> So we want the general design that it will be applied to every single pattern?

We need two design both List and SinglePattern.
And current two suggestions are design for SinglePattern.

**Comment by TroyTae** [comment]
Temp Design
 - List page:
![image](https://user-images.githubusercontent.com/20078201/78465501-84014500-7731-11ea-8227-5a5686171858.png)
 - Each pattern pages:
![image](https://user-images.githubusercontent.com/20078201/78465511-97141500-7731-11ea-8d33-83f0904bb14f.png)

**Comment by LoukasPap** [comment]
How about adding a title at the top? So that the guests can see what the website is about?
Also, I though that if we have Still-Life next to Oscillator, the viewer will not have to scroll for a long time.
https://www.figma.com/file/YR3SziYxNQcIlZgwt9vAfq/GOL?node-id=32%3A3

**Comment by TroyTae** [comment]
@LoukasPap 
It's good suggestion!
I update like this:
![image](https://user-images.githubusercontent.com/20078201/78761627-d3f43c00-79bd-11ea-9530-0b1fdba041a2.png)
