### ISSUE TITLE
feat: playground page

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#756]
Requirement:
- This page needs three buttons (start / stop / reset)
  1. start => executive method `startLife`
  2. stop => executive method `stopLife`
  3. reset => reset to the pattern which sets first
- Pattern can handle with click (Like this: https://lukestorry.github.io/bool-array-filler/)
- Pattern's size can customize with two input (one text input for columns, one text input for rows)

**Comment by LoukasPap** [comment]
Me and @DinosXa can handle that! 😄

**Comment by DinosXa** [comment]
yes we will provide maximum effort in order to tackle this task :)

**Comment by aimorris** [comment]
@LoukasPap @DinosXa Are you still continuing work on this? If not, I'll take it up.

**Comment by DinosXa** [comment]
Yes we are :)

**Comment by LoukasPap** [comment]
Yes @aimorris we are working on it 😃

**Comment by LoukasPap** [comment]
@TroyTae Do you want the cells on the corner, check only the neighbors next to them, or check the neighbors from the opositte side of the table too?
**For example**: we have a 10x10 table. The cell on _index (0, 0)_, does not have neighbors at (-1, 0), (-1, -1) and (0, -1). In that case, do you want to check the indexes (10, 1), (10, 10) and (1, 10)?

**Comment by TroyTae** [comment]
@LoukasPap 
We need to check all of neighbors.
But (-1, 0), (-1, -1) and (0, -1) will be always dead status(=0).
And this algorithm already implement in engine!
