### ISSUE TITLE
feat: 258P3 on Achim's p11

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#786]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/79976026-ec447a80-84d6-11ea-8f82-f189c405dafc.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/258P3-on-achims-p11.ts

If you wanna tackle this issue, please leave comment.  
I'll assign to you!  

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by austinHufstetler** [comment]
Hi, first time contributing to this repo! Could I work on this one?

**Comment by TroyTae** [comment]
Sure!
