### ISSUE TITLE
feat: Boat tie eater head

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#81]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/66694418-04e50400-ecee-11e9-9fa1-3ba182ced1d5.png)

Please work at this line: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/boat-tie-eater-head.ts

**Comment by hasalassh** [comment]
@TroyTae Let me work on this...!
