### ISSUE TITLE
feat: Boat tie eater tail

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#82]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/66694429-2e9e2b00-ecee-11e9-920d-4d49b7d597e0.png)

Please work at this line: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/boat-tie-eater-tail.ts

**Comment by hasalassh** [comment]
@TroyTae Let me work on this...!
