### ISSUE TITLE
feat: Boat tie long boat

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#83]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/66694442-4aa1cc80-ecee-11e9-84c8-c1a0190c3c24.png)

Please work at this line: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/boat-tie-long-boat.ts

**Comment by hasalassh** [comment]
@TroyTae  Let me work on this...!
