### ISSUE TITLE
feat: 6 bits

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#832]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/81824595-9e201580-9570-11ea-8a07-222aee04c9dd.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/shuttle/6-bits.ts

If you wanna tackle this issue, please leave comment.  
I'll assign to you!  

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by fejimene** [comment]
Hi, I can help with this

**Comment by fejimene** [comment]
Created PR: https://github.com/TroyTae/game-of-life/pull/838
