### ISSUE TITLE
feat: Boat tie long snake

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#84]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/66694449-64431400-ecee-11e9-9b57-ae0b74267e0f.png)

Please work at this line: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/boat-tie-long-snake.ts

**Comment by dschandrasekara** [comment]
@TroyTae let me do it.

**Comment by dschandrasekara** [comment]
created PR https://github.com/TroyTae/game-of-life/pull/102 please, review and let me know ur feedback
