### ISSUE TITLE
feat: Boat tie ship

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#85]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/66694458-7f158880-ecee-11e9-926b-f7799484e61a.png)

Please work at this line: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/boat-tie-ship.ts

**Comment by dschandrasekara** [comment]
@TroyTae let me create PR for this

**Comment by dschandrasekara** [comment]
created PR https://github.com/TroyTae/game-of-life/pull/103 please, review and let me know ur feedback
