### ISSUE TITLE
feat: Boat with cis-tail

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#87]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/66694546-86896180-ecef-11e9-9f07-569080e78c52.png)

Please work at this line: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/boat-with-cis-tail.ts

**Comment by HencoSmith** [comment]
On it 👍

**Comment by TroyTae** [comment]
closed by #96
