### ISSUE TITLE
feat: Boat with hooked tail

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#88]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/66694558-9c972200-ecef-11e9-9a47-1937d0ef4cd2.png)

Please work at this line: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/boat-with-hooked-tail.ts

**Comment by dschandrasekara** [comment]
@TroyTae let me work on this

**Comment by dschandrasekara** [comment]
please, review the PR https://github.com/TroyTae/game-of-life/pull/101 and let me know ur feedback
