### ISSUE TITLE
CONTRIBUTING.md needs update

### ISSUE THREAD

**Issue by LoukasPap** [TroyTae/game-of-life#883]
In the 6th step of contributing, where it explains how to add colors, it needs a small change.
![image](https://user-images.githubusercontent.com/44159938/84367995-b1f58080-abdd-11ea-9061-4c9efb0a240f.png)
The contributor must only write 
```
'',
'',
'',
```
for **dead**, **survive**, and **background** color accordingly.

**Comment by TroyTae** [comment]
Now data format is changed from typescript to json.
So we can maintain current contents!
