### ISSUE TITLE
feat: Babbling brook 1

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#884]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/84511825-13167480-ad02-11ea-8238-21fb60c575fa.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/babbling-brook/babbling-brook-1.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!  

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by therajdeepbiswas** [comment]
Available to help

**Comment by therajdeepbiswas** [comment]
Available to help

**Comment by therajdeepbiswas** [comment]
note to self: 18x13
