### ISSUE TITLE
feat: Baker's dozen

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#885]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/84512034-5bce2d80-ad02-11ea-9c26-241ea6c4d412.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/bakers-dozen.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!  

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by therajdeepbiswas** [comment]
Available to help

**Comment by therajdeepbiswas** [comment]
Found a very efficient way to convert these grid images into binary. Please mention the dimensions of the grid along with the issue, next time onward, that would speed things up a lot.
For example: this one would be Baker's dozen: 25x14
