### ISSUE TITLE
feat: Boss

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#887]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/84639022-c1a0fc00-af32-11ea-9c50-d02548cb04b6.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/billiard-table/boss.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!  

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by gvasquez11** [comment]
Hello, I'd like to take this issue :)
