### ISSUE TITLE
feat: Burloaferimeter

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#888]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/84639135-ec8b5000-af32-11ea-83f8-d3206e387782.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/billiard-table/burloaferimeter.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!  

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by SimonPettersson92** [comment]
I'd like to try this.

**Comment by therajdeepbiswas** [comment]
@SimonPettersson92 are you creating a PR?

**Comment by TroyTae** [comment]
closed by #890
