### ISSUE TITLE
feat: Boat with long tail

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#89]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/66694569-b0428880-ecef-11e9-8304-53040921a9e3.png)

Please work at this line: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/boat-with-long-tail.ts

**Comment by dschandrasekara** [comment]
@TroyTae let me work on this

**Comment by dschandrasekara** [comment]
Created PR -> https://github.com/TroyTae/game-of-life/pull/100
