### ISSUE TITLE
feat: Bipole tie pseudo-barberpole

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#892]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/84717653-62ce9780-afb1-11ea-987e-5c0b3f113a1b.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/muttering-moat/bipole-tie-pseudo-barberpole.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!  

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by JapneetSingh5** [comment]
I’ll be glad if I can work on this!
