### ISSUE TITLE
feat: Bipole tie ship

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#893]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/84717698-914c7280-afb1-11ea-89c8-b79d6580af43.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/muttering-moat/bipole-tie-ship.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!  

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by therajdeepbiswas** [comment]
Taking up.
