### ISSUE TITLE
feat: Bipole tie snake

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#894]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/84717747-ba6d0300-afb1-11ea-898f-b10ae78f704a.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/muttering-moat/bipole-tie-snake.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!  

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by therajdeepbiswas** [comment]
Taking up.
