### ISSUE TITLE
feat: Bipole

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#895]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/84717801-e8eade00-afb1-11ea-80e2-3b0feb5381e9.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/muttering-moat/bipole.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!  

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by therajdeepbiswas** [comment]
Taking up.
