### ISSUE TITLE
feat: Boat tie bipole

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#898]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/84841539-8f4fe580-b07d-11ea-9802-b4e2d21a6e05.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/muttering-moat/boat-tie-bipole.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!  

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by Radoogle** [comment]
Hello,
I would like to contribute!
I'm new to git, so I might need some instructions, but I am willing to follow the steps and bring my contribution to this repo.
I have forked and cloned locally, I followed the Development Process steps, skipped step 6 (for now) and at step 7 (Run npm run test:lint and validate your code) I get a bunch of errors like: " A space is required after ','                 comma-spacing".

And now I'm not sure what I should do next?
I'll make a PR for checkup.

**Comment by TroyTae** [comment]
Hmmm it's strange
![image](https://user-images.githubusercontent.com/20078201/84962590-2aaa8e80-b142-11ea-8613-ed032e5140dc.png)
It seems build/lint process is success
Maybe some of your local files effect to them
Anyway no worries, your PR is perfect!
