### ISSUE TITLE
feat: Boat tie tripole

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#899]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/84841576-b0b0d180-b07d-11ea-9562-16ffd021c256.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/muttering-moat/boat-tie-tripole.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!  

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by Radoogle** [comment]
Hello again!
How do I tackle the step 6 : 
--
This step is optional
Put colors inside the pattern. Write down:
deadColor: '',
surviveColor: '',
backgroundColor: '',
Then, fill the single quotation marks with colors from this page
--
which file should I change and how exactly? Do you have an example please?

**Comment by TroyTae** [comment]
@Radoogle 
Oops I already merger your PR before this comment..
You can add color like this:
```

{
  "title": "Boat tie tripole",
  "life": [
    [0, 0, 0],
    [0, 0, 0],
    [0, 0, 0]
  ],
  "deadColor": "#FF0000",
  "backgroundColor": "blue"
}
```

**Comment by Radoogle** [comment]
@TroyTae 
Still a couple of questions regarding the colors:
 - what about "surviveColor", you don't need it?
 - how to choose the colors in the same pattern and how different should they be for every file?
 - and can I go over the files and add the colors or do you need to open some issues for this?

**Comment by TroyTae** [comment]
@Radoogle 
Maybe I'll remove description about color option soon.
Because we have plan to add color picker in page.
Finally I hope the user can change color in real time.
So.. if you interested in this issue, please watch our repo!
I'll execute this plan after making unit test :)
