### ISSUE TITLE
feat: Boat with long^3 tail

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#90]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/66694583-d5cf9200-ecef-11e9-8922-e974deb97c35.png)

Please work at this line: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/boat-with-long3-tail.ts

**Comment by luhego** [comment]
I created a pull request for this issue:
https://github.com/TroyTae/game-of-life/pull/95
