### ISSUE TITLE
feat: Blocked p4 t-nose

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#902]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/84963130-7d387a80-b143-11ea-9260-599dbf1b21ff.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/t-nose/blocked-p4-t-nose.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!  

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by Radoogle** [comment]
Hi, I have created this pattern, but can't create the PR.
Any hints? (I did commit from git bash).
