### ISSUE TITLE
feat: Beehive on griddle

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#908]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/85238263-d9630d80-b467-11ea-8def-ad46db3373eb.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/beehive-on-griddle.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!  

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by alexanderbrown21** [comment]
i would take this on!
