### ISSUE TITLE
feat: Beehive on long hook eating tub

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#909]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/85238296-06172500-b468-11ea-9b3f-db3fa090d212.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/beehive-on-long-hook-eating-tub.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!  

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by Zedex7** [comment]
Hey @TroyTae, I can work on this.
