### ISSUE TITLE
feat: Boat with very long tail

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#91]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/66694588-e5e77180-ecef-11e9-8cbe-6367a5289029.png)

Please work at this line: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/boat-with-very-long-tail.ts

**Comment by juanmagutierrez** [comment]
I would like to do this
