### ISSUE TITLE
feat: Beehive test tube baby

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#910]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/85238396-889fe480-b468-11ea-8e43-bb0ec1eb113b.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/beehive-test-tube-baby.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!  

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by quowtf** [comment]
Hi, I want to help with this pattern

**Comment by quowtf** [comment]
I was following the guide of contribution, but step 7 fail with `✖ 74621 problems (74621 errors, 0 warnings)`, I try to solve this in these ways.

1. modify test:lint script with `"test:lint": "eslint --ext .ts src/ --ignore-pattern 'src/build/*'"`
2. by running `fix:lint` script before step 7

If one of these options is ok to you, I would like to modify the guide and send another PR

**Comment by TroyTae** [comment]
@quowtf 
Oops that's my mistake, I ignore that just in my local environment.
Thank you :)
