### ISSUE TITLE
feat: Beluchenko's other p37

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#911]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/85346248-ddf2f900-b52f-11ea-8b8b-fbda2be04ab1.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/beluchenkos-other-p37.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!  

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by Zedex7** [comment]
Hey @TroyTae , I can work on this.
