### ISSUE TITLE
feat: Boat-tie

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#92]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/66694666-e3394c00-ecf0-11e9-9df9-3e4b981ba604.png)

Please work at this line: https://github.com/TroyTae/game-of-life/blob/master/src/life/still-life/boat-tie.ts

**Comment by Joel-hanson** [comment]
Shall I take this up @TroyTae

**Comment by TroyTae** [comment]
@Joel-hanson
Sure! Feel free to send PR :)

**Comment by Joel-hanson** [comment]
Hi @TroyTae ,

Hope this PR #93 solve this issue 

Thanks in advance.
