### ISSUE TITLE
feat: Bent keys

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#920]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/85483636-2b3e9b80-b600-11ea-9f16-340a718ff2fa.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/bent-keys.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!  

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by BrayanCaro** [comment]
I want to fix this :)

**Comment by harsh-doshii** [comment]
Even I would like to work on this if it's okay. Thanks.
