### ISSUE TITLE
feat: Biting off more than they can chew

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#921]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/85483684-490c0080-b600-11ea-8585-b67a10e1b362.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/biting-off-more-than-they-can-chew.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!  

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by mmaciass** [comment]
I wanna fix this issue
