### ISSUE TITLE
feat: Blinkers bit pole

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#922]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/85483738-62ad4800-b600-11ea-8b21-cf3fa37082a5.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/blinkers-bit-pole.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!  

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by roniel-rhack** [comment]
I wanna fix this issue
