### ISSUE TITLE
feat: Block on griddle

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#923]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/85483861-9d16e500-b600-11ea-8ed1-ed64d8337d71.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/block-on-griddle.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!  

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by mmaciass** [comment]
I wanna fix this issue
