### ISSUE TITLE
feat: Blocker

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#941]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/86676455-968f6100-c035-11ea-99da-447f6c1a6843.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/blocker.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!  

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by me-manikanta** [comment]
Hey,
I'll work on this can you assign me to this issue
