### ISSUE TITLE
feat: Blocks on griddle

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#942]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/86676567-b6268980-c035-11ea-89e5-8a5db1ef2ac1.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/blocks-on-griddle.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!  

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by mmaciass** [comment]
I wanna fix this issue
