### ISSUE TITLE
feat: Blonker

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#943]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/86676681-d48c8500-c035-11ea-8217-aa9cd30a41f8.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/blonker.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!  

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by mmaciass** [comment]
I wanna fix this issue
