### ISSUE TITLE
feat: Blonker on Rich's p16

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#944]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/86677044-3220d180-c036-11ea-872b-13d83854fc82.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/blonker-on-richs-p16.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!  

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by AlacritousCreature** [comment]
hey! I want to work on this issue. Can you assign it to me?

**Comment by AlacritousCreature** [comment]
Hi!.. the second pull request up here is updated one. Please ignore the first pull request.
