### ISSUE TITLE
feat: By flops

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#948]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/87418301-67b45480-c60c-11ea-8cdc-9a75871fa2f1.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/by-flops.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!  

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by jackpalaia** [comment]
I'm interested in working on this.
