### ISSUE TITLE
feat: Buckingham's p13

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#950]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/87418390-94686c00-c60c-11ea-8c60-3c02f069124a.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/buckinghams-p13.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!  

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by JohnMachado11** [comment]
Interested!
