### ISSUE TITLE
feat: Bottle

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#951]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/87418531-c974be80-c60c-11ea-9a63-4bcb161d59c4.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/bottle.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!  

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by AidenKerr** [comment]
interested!
