### ISSUE TITLE
feat: Boring p24

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#952]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/87418636-f9bc5d00-c60c-11ea-9ae0-040a898da812.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/boring-p24.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!  

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by Axhat** [comment]
I am interested 😁

**Comment by Axhat** [comment]
#953
