### ISSUE TITLE
feat: Boat tie spark coil

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#957]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/87756517-0080e500-c844-11ea-88d6-9157f652d9f4.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/boat-tie-spark-coil.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!  

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by Suyyashaa** [comment]
Can I work on this issue?
