### ISSUE TITLE
feat: Boat tie quadpole

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#958]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/87756647-3faf3600-c844-11ea-99f4-5eb5c935e5a7.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/boat-tie-quadpole.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!  

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by Suyyashaa** [comment]
Can I work on this issue?
