### ISSUE TITLE
feat: Boat test tube baby

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#959]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/87756750-708f6b00-c844-11ea-9593-0c55c231d633.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/boat-test-tube-baby.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!  

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by Mrskillful** [comment]
Huh, interesting shape... 
I'd like to contribute to this issue.
