### ISSUE TITLE
feat: Boat on griddle

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#960]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/87756835-97e63800-c844-11ea-8903-142c6e22603a.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/boat-on-griddle.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!  

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by aalten77** [comment]
Hello, this is my first time contributing to an open-source project. I am happy to stumble across this issue with a very easy guide to follow. Thank you! I will send a PR
