### ISSUE TITLE
feat: Cauldron

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#972]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/88348868-81326a80-cd89-11ea-88bf-59922d757f5e.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/billiard-table/cauldron.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!  

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by JohnMachado11** [comment]
Interested 😁
