### ISSUE TITLE
feat: Champagne glass

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#973]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/88348929-a9ba6480-cd89-11ea-956c-f79b9c856af1.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/billiard-table/champagne-glass.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!  

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by JohnMachado11** [comment]
Interested 😁
