### ISSUE TITLE
feat: Chemist

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#974]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/88349013-e71ef200-cd89-11ea-97ab-eb16af583de8.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/billiard-table/chemist.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!  

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by JohnMachado11** [comment]
Interested 😁
