### ISSUE TITLE
feat: Clock 2

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#978]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/88445831-59fa9c80-ce60-11ea-81c0-d61c0816d9f6.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/billiard-table/clock-2.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!  

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by JohnMachado11** [comment]
I'll handle it 👍🏻
