### ISSUE TITLE
feat: Cousins

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#979]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/88445861-7991c500-ce60-11ea-9328-52afa24127fb.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/billiard-table/cousins.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!  

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by JohnMachado11** [comment]
I'll handle it 👍🏻
