### ISSUE TITLE
feat: Crowd

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#980]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/88445896-b9f14300-ce60-11ea-866c-428277e4c427.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/billiard-table/crowd.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!  

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by minahabibm** [comment]
can I get assigned?
