### ISSUE TITLE
feat: Carrier tie bipole

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#981]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/88450930-b0320480-ce8d-11ea-9d82-7cbc1df392d3.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/muttering-moat/carrier-tie-bipole.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!  

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by vsushruth** [comment]
Can this be assigned to me?
