### ISSUE TITLE
feat: Cha cha

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#982]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/88450949-e2436680-ce8d-11ea-9fd8-2369c0d17fc9.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/muttering-moat/cha-cha.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!  

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by vsushruth** [comment]
Can this be assigned to me?
