### ISSUE TITLE
feat: Circle of fire

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#983]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/88450964-0606ac80-ce8e-11ea-9def-f17b3b8f14a4.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/muttering-moat/circle-of-fire.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!  

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by MrMirror21** [comment]
Can I get assign to this one?
