### ISSUE TITLE
feat: Clock

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#989]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/88479767-7e539780-cf8c-11ea-946e-d8bb88690c94.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/muttering-moat/clock.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!  

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by JohnMachado11** [comment]
I'll work on this
