### ISSUE TITLE
feat: Cuphook

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#990]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/88479780-9aefcf80-cf8c-11ea-8705-ce164430d7b2.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/muttering-moat/cuphook.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!  

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by JohnMachado11** [comment]
I'll work on it :)
