### ISSUE TITLE
feat: Cyclic

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#991]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/88479798-b9ee6180-cf8c-11ea-876e-275ea59483db.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/muttering-moat/cyclic.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!  

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by JohnMachado11** [comment]
I'll work on this
