### ISSUE TITLE
feat: Carnival shuttle

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#992]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/88479914-a0014e80-cf8d-11ea-8617-4eb90d41ff89.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/shuttle/carnival-shuttle.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!  

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by JohnMachado11** [comment]
I can do it
