### ISSUE TITLE
feat: Centinal

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#993]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/88479947-c6bf8500-cf8d-11ea-9cb9-9778dfa37575.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/shuttle/centinal.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!  

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by JohnMachado11** [comment]
I'll do it
