### ISSUE TITLE
feat: Candlefrobra

### ISSUE THREAD

**Issue by TroyTae** [TroyTae/game-of-life#995]
Let's make this pattern:
![image](https://user-images.githubusercontent.com/20078201/88480078-c07dd880-cf8e-11ea-8783-34aa46946af1.png)

Please work at this file: https://github.com/TroyTae/game-of-life/blob/master/src/life/oscillator/candlefrobra.json

If you wanna tackle this issue, please leave comment.  
I'll assign to you!  

Are you first time for contributing this repo?  
Please read this [guide](https://github.com/TroyTae/game-of-life/blob/master/.github/CONTRIBUTING.md) :)

**Comment by JohnMachado11** [comment]
I'll do it

**Comment by StijnLammers** [comment]
Can I take on this issue?

**Comment by StijnLammers** [comment]
So this is the first time I'm contributing to any github project, and I'm kind of confused.
I edited the file to match the pattern and all.
Now I saved it and commited to master, is that all I got to do?

**Comment by TroyTae** [comment]
@StijnLammers 
Yes that's all.
Please send us PR!
